### ISSUE TITLE
is TBC playable?

### ISSUE THREAD

**Issue by yuritsuki** [WowLegacyCore/HermesProxy#10]
You can login, create character, start walking. And that's all. Can't talk to npcs, cast spells on mobs and etc.

![image](https://user-images.githubusercontent.com/46904553/169282698-25c7cd63-4ab1-4014-9e2f-b9cb0b198447.png)

**Comment by MaxtorCoder** [comment]
What client version did you take?

**Comment by yuritsuki** [comment]
> What client version did you take?

2.5.2

**Comment by ratkosrb** [comment]
Should be fixed in https://github.com/WowLegacyCore/HermesProxy/commit/9ddcf44d4c7bcb5db448519fea9a78231065e264

**Comment by yuritsuki** [comment]
> Should be fixed in [9ddcf44](https://github.com/WowLegacyCore/HermesProxy/commit/9ddcf44d4c7bcb5db448519fea9a78231065e264)

Can you build it pls? I can check it.

**Comment by ratkosrb** [comment]
https://github.com/WowLegacyCore/HermesProxy/releases/tag/v2.0
