### ISSUE TITLE
character cant ressurect on everlook (stuck dead no rez window)

### ISSUE THREAD

**Issue by jheldridge** [WowLegacyCore/HermesProxy#101]
1.14 is the future of vanilla pservers we need to get this working brothers..currently atm cant ressurect on the everlook pserver even when standing on top of your body the window doesnt show up..brotalnia recently fixed the warden issue that seems to be working great again no more black screen but this is the next issue :)
![rez](https://user-images.githubusercontent.com/92758178/202864035-dff1caa9-d2e1-4b7b-8b72-ab3fc51a7a4a.png)

any help would be much appreciated ! thanks

**Comment by 0blu** [comment]
Type `/script RetrieveCorpse()` when close.
Will be tracked by #51
