### ISSUE TITLE
Infinite download files for the game.

### ISSUE THREAD

**Issue by Minorous** [WowLegacyCore/HermesProxy#106]
I am using google translator.
The game, Hermesproxy and launcher are loaded and run the game, you can go in and play, but after restarting the shortcut created on the desktop, all files are downloaded to the desktop again. To avoid this, you need to write its directory in the properties of the launcher shortcut, or create a new launcher shortcut from the folder already installed. Thank you for your work!

**Comment by 0blu** [comment]
Thanks, it is fixed in the latest version.
https://github.com/0blu/EverlookClassicLauncher/releases
