### ISSUE TITLE
Stuck on "Logging in to game server"

### ISSUE THREAD

**Issue by blackcorridors** [WowLegacyCore/HermesProxy#114]
Using the latest version of HermesProxy, 11/25 and latest Arctium Launcher.
Everytime i try to login to Everlook, the game gets stuck on Logging in to game server until it disconnects after a minute.
That is the SS of HermesProxy after it happens.
![Screenshot 2022-11-25 085833](https://user-images.githubusercontent.com/110686811/203930450-276455a7-732d-4f69-91f0-0f967619eba8.png)
I double checked and everything is set up correctly.

**Comment by 0blu** [comment]
Hmm interesting, can you try one of these fixes:
1. Restart your pc
2. Enable `Optimize Network for Speed` (it's under game options `System` -> `Network`)
