### ISSUE TITLE
When I modify ExternalAddress，Program error

### ISSUE THREAD

**Issue by HBcc75** [WowLegacyCore/HermesProxy#115]
“14:34:14 |  Server  | Server          | Starting Hermes Proxy...
14:34:14 |  Server  | Server          | Version 2022-11-25 *official* 3.3.0
14:34:14 |  Storage | GameData        | Loading data files...
14:34:14 |  Server  | VersionChecker  | Loaded 833 legacy opcodes.
14:34:14 |  Server  | VersionChecker  | Loaded 1639 modern opcodes.
14:34:15 |  Storage | GameData        | Finished loading data.
14:34:15 |  Server  | Server          | Starting REST service...
14:34:15 | Halting process...
 Error   | AsyncAcceptor   | System.Net.Sockets.SocketException (10049): The requested address is invalid in its context
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError , String )
   at System.Net.Sockets.Socket.DoBind(EndPoint , SocketAddress )
   at System.Net.Sockets.Socket.Bind(EndPoint )
   at System.Net.Sockets.TcpListener.Start(Int32 )
   at System.Net.Sockets.TcpListener.Start()
   at Framework.Networking.AsyncAcceptor.Start(String ip, Int32 port) in D:\a\HermesProxy\Framework\Networking\AsyncAcceptor.cs:line 44
14:34:15 |  Network | SocketManager   | StartNetwork failed to Start AsyncAcceptor
14:34:15 |  Server  | Server          | Failed to initialize Rest Socket Server
”
SO 
When I modify ExternalAddress，Program error；
fantastic job.

**Comment by Fabi** [comment]
more details please ty

**Comment by HBcc75** [comment]
> more details please ty


Sorry, my English is limited. When I modify "HermesProxy.config: key="ServerAddress" value, an error occurs when I start HermesProxy.exe；
I would like to ask whether the ServerAddress is prohibited to modify or something else

**Comment by 0blu** [comment]
Can you show us what your config looks like?

**Comment by HBcc75** [comment]
> 你能告诉我们你的配置是什么样的吗？
sure ,Is it now limited to server side configuration
[HermesProxy.zip](https://github.com/WowLegacyCore/HermesProxy/files/10095984/HermesProxy.zip)

**Comment by ratkosrb** [comment]
I think you are confusing ServerAddress with ExternalAddress.

ServerAddress - this is the address of the 1.12 or 2.4.3 server you want to play on

ExternalAddress - this is the address on which modern clients can connect to Hermes (if you want to run Hermes on a different computer and have external clients connect to it)

**Comment by HBcc75** [comment]
> 


> I think you are confusing ServerAddress with ExternalAddress.
> 
> ServerAddress - this is the address of the 1.12 or 2.4.3 server you want to play on
> 
> ExternalAddress - this is the address on which modern clients can connect to Hermes (if you want to run Hermes on a different computer and have external clients connect to it)

As you said I want to run Hermes on a different computer and have external clients connect to it；Some friends want to play 1.14.0 WOW through Hermes

**Comment by ratkosrb** [comment]
Try reverting this commit and see if it solves the problem.
https://github.com/WowLegacyCore/HermesProxy/commit/ae1b7d54ef963bd84062ee5a00e1887755f49431

```
git revert ae1b7d54ef963bd84062ee5a00e1887755f49431
```

**Comment by 0blu** [comment]
@ratkosrb
I dislike to listen on `0.0.0.0` by default.
Should I change this to `IPAddress.Parse(Framework.Settings.ExternalAddress).IsLoopback ? "127.0.0.1" : "0.0.0.0"`?

**Comment by ratkosrb** [comment]
sounds good
