### ISSUE TITLE
Stepping on Zep to Grom'Gol from UC instant disconnect

### ISSUE THREAD

**Issue by arm358** [WowLegacyCore/HermesProxy#121]
**Describe the bug**
As soon as I step on the zeppelin to Grom'Gol from UC, I get disconnected by the server. This disconnect happens before the ship is even moving--i.e. instantly as soon as I get on. Every other Zepp/ship works fine. Have to go UC->Org->Grom'Gol instead.

**Game Server**
Everlook

**Hermes Proxy Version**
Hermes Proxy Version
Latest release for Linux Ubuntu (v3.2 https://github.com/WowLegacyCore/HermesProxy/commit/b0dcbb87248df82c74f95fcb92c9dc67b57c8b52)
Arctium launched through Steam Proton (Experimental)

**Comment by 0blu** [comment]
Already Tracked by #88
