### ISSUE TITLE
Wrong roll description

### ISSUE THREAD

**Issue by Fearyii** [WowLegacyCore/HermesProxy#129]
**Describe the bug**
After being in a group and selecting need on a green item that dropped it says i greeded instead of need.

**Game Server**
Everlook

**Hermes Proxy Version**
Using winterspring launcher, hermes version: 16:12:09 |  Server  | Server          | Version 2022-11-25 *official* 3.3.0
![image](https://user-images.githubusercontent.com/111935564/204301514-ddfd532b-2714-482b-9bbb-bf5cfa2adcf5.png)

**Comment by gnarly1017** [comment]
same for me
