### ISSUE TITLE
Blink breaks camera after flight path

### ISSUE THREAD

**Issue by Daribon** [WowLegacyCore/HermesProxy#137]
**Describe the bug**
On a gnome mage if you take flight path and then use blink after landing, your camera will be stuck in wrong position.
The size of your model collision will be changed to something much greater than that of a normal gnome.

**Game Server**
VMaNGOS

**Hermes Proxy Version**
![WindowsTerminal_kQPZSKj6tp](https://user-images.githubusercontent.com/6137576/204653984-955eb2ca-7de4-4379-8cfd-4cdf7a8598c5.png)

**Comment by Daribon** [comment]
Fixed in https://github.com/WowLegacyCore/HermesProxy/commit/08ac16966ae592ebcbc1d285587ed6480d2b11ed

**Comment by Daribon** [comment]
Mounting up fixes it, but the next blink the camera will break again.

**Comment by Daribon** [comment]
This bug also happens if you mount up and blink afterwards.

**Comment by 0blu** [comment]
Fixed with #246
