### ISSUE TITLE
TBC is still buggy

### ISSUE THREAD

**Issue by yuritsuki** [WowLegacyCore/HermesProxy#14]
![image](https://user-images.githubusercontent.com/46904553/169671078-85368e79-efcd-4283-b9cc-a5be0c317c49.png)

**Comment by MaxtorCoder** [comment]
This is still a WIP (Work in Progress)

**Comment by yuritsuki** [comment]
On second time spells have loaded. But it still doesnt load items

**Comment by yuritsuki** [comment]
> This is still a WIP (Work in Progress)

Oh, ok. Sorry then, I didn't find any info about status of tbc implementation

**Comment by MaxtorCoder** [comment]
> > This is still a WIP (Work in Progress)
> 
> Oh, ok. Sorry then, I didn't find any info about status of tbc implementation

That's fine! Dw :D

**Comment by ratkosrb** [comment]
What server is this? I don't have such a problem, my characters load fine.
