### ISSUE TITLE
Unable to join /world or /6

### ISSUE THREAD

**Issue by NiceLikeTryce** [WowLegacyCore/HermesProxy#140]
**Describe the bug**
When attempting to join /world or /6 nothing happens.

**Game Server**
Everlook

**Hermes Proxy Version**
[Version 2022-11-29](https://github.com/WowLegacyCore/HermesProxy/releases/tag/v3.4)

**Comment by 0blu** [comment]
Are you sure you have downloaded the version from GitHub?
![image](https://user-images.githubusercontent.com/7039020/204845447-add3bf18-837c-41da-9c05-2cd722eeb37f.png)
It is working for me on Everlook
