### ISSUE TITLE
The character will become smaller after flying

### ISSUE THREAD

**Issue by xicyboy** [WowLegacyCore/HermesProxy#143]
The character will become smaller after flying，on everlook

**Comment by 0blu** [comment]
What version of HermesProxy are you using?
Where did you got this version from?

What race where you playing?
How did you notice you got smaller? (Did `[Elixir of Giant Growth]` run out?)

**Comment by xicyboy** [comment]
i used HermesProxy v3.4 on everlook,and here is my video [HermesProxy](https://youtu.be/7K6qCz_-qkk)

**Comment by 0blu** [comment]
Thanks for the video!
This is also happening if you mount a normal mount.

We are sending `MoveSetCollisionHeight` without explicit `Scale` thus it is set to default `1.0f`.
https://github.com/WowLegacyCore/HermesProxy/blob/a0ce86bbfff9c0b4c9840f7240ac57b8246548fb/HermesProxy/World/Client/PacketHandlers/UpdateHandler.cs#L1625-L1630
We would need to cache our last scale somewhere.

I feel like `GameSessionData` is getting more and more crowded, what do you think? @ratkosrb

**Comment by xicyboy** [comment]
thank you for answering my questions so late, even though it's daytime.your job is cool,
