### ISSUE TITLE
Can't Res?

### ISSUE THREAD

**Issue by lilserp** [WowLegacyCore/HermesProxy#144]
I can't res at my corpse unless resurrected. This only occurs out in the world. I get this error:
![Screenshot_8](https://user-images.githubusercontent.com/119501515/204852166-b6def51d-cd41-4e4b-a413-a3b623d81ec6.png)

Everlook - Arctium Launcher

Version 2022-11-29

**Comment by 0blu** [comment]
Ah thx much!

**Comment by 0blu** [comment]
I have some more question:
- Below `PP:` was there your username?
- Did you die here?
![image](https://user-images.githubusercontent.com/7039020/204856124-341bab19-6d6d-4008-a3e7-c115af3ed96b.png)

**Comment by SuperGini** [comment]
![iSeeDeadPppl](https://user-images.githubusercontent.com/58910040/204920075-2a3bcde5-ae16-4062-8205-4d6d6704895b.png)

this is the second time i die and can't resurrect. The resurrect window does not apear. I have to log with the 1.12.1 client. I' using the 1.14.(40618) client

**Comment by ratkosrb** [comment]
The issue is caused by hiding your Helm and Cloak. Go into Interface settings and enable showing the Helm and Cloak.

**Comment by SuperGini** [comment]
ok. i'll try that.

**Comment by SuperGini** [comment]
ok. I enabled showing the Helm and Cloak. And now i can resurrect. If you can fix this bug (because i dont like showing cloak and helm) it would be appreciated:D. You are doing a very good job.
