### ISSUE TITLE
1.12 Threat to 1.14

### ISSUE THREAD

**Issue by Fearyii** [WowLegacyCore/HermesProxy#145]
**Describe the bug**
Its not really a bug, but raiding on 1.14 does not show threat to 1.12 clients that are using KTM.
Using the detail threat meter I can see everyone's threat perfectly and accurately, but is it possible to make it so 1.12 client can see our threat since raid lead is not really happy with people using this client due to that reason.

Game Server:
Everlook

**Hermes Proxy Version**
Latest from winterspring launcher

**Comment by 0blu** [comment]
Same is #109

**Comment by 0blu** [comment]
@Fearyii 
> Using the detail threat meter I can see everyone's threat perfectly and accurately
Does your version of Details also show the threat of people who are not using this Addon?

**Comment by Fearyii** [comment]
> @Fearyii
> 
> > Using the detail threat meter I can see everyone's threat perfectly and accurately
> 
> Does your version of Details also show the threat of people who are not using this Addon?

Yes, not in raids tho only dungeons probably the same for raid. 
Pretty sure its becuase of the threat api added to the client from blizzard

**Comment by 0blu** [comment]
What version of details are you using? Can you post a link please.

**Comment by Fearyii** [comment]
Details version says its c219
![image](https://user-images.githubusercontent.com/111935564/205116236-b8df15c9-f2ff-41b0-a195-05fceb9f76e2.png)
