### ISSUE TITLE
Power Word: Fortitude buff tooltip on other players shows a value of 0 

### ISSUE THREAD

**Issue by apav** [WowLegacyCore/HermesProxy#148]
**Describe the bug**
The Power Word Fortitude buff has a value of 0 on other players. So far this is the only buff or debuff I have seen that doesn't show the correct value.

![fortitude bug](https://user-images.githubusercontent.com/8137930/204950112-6d02b37a-841f-4e2d-af2b-c5d4a5f788f0.jpg)

**Game Server**
Everlook

**Hermes Proxy Version**
3.4.0

**Comment by 0blu** [comment]
I guess we need to add `effectBasePoints{1,2,3}` CSV and modify `ReadAuraSlot(...)` to send the points to the client.
Do descriptions scale with gear / stats (like int) in vanilla?

**Comment by ratkosrb** [comment]
The buff amount could scale with a talent buffing it, and you have no way of knowing what talents other players have.

**Comment by SuperGini** [comment]
I can confirm this bug.  This shows 0 stamina with or without the improved Power Word Fortitude talent point.
Running Hermes 3.4.0. WoW 1.14.0 client (40618). Curently having rank 2 spell the default value is 20 stamina points and with 1 point in the talent i have 23 stamina points. When i buffed myself or other the toltip shows 0 stamina points. Server -> Everlook

![1](https://user-images.githubusercontent.com/58910040/205254459-14858b67-35a4-4dc0-89eb-10feca360c87.png)
![2](https://user-images.githubusercontent.com/58910040/205254468-d477b26a-412d-45ee-a264-2a0c08b8cf88.png)
![3](https://user-images.githubusercontent.com/58910040/205254469-c5cb9394-9b07-48e2-bda5-41ec8c8cde63.png)
![4](https://user-images.githubusercontent.com/58910040/205254472-2592325c-6f56-4c98-bab3-83fe6e7055d4.png)
