### ISSUE TITLE
Unable to validate game version

### ISSUE THREAD

**Issue by yjwcw** [WowLegacyCore/HermesProxy#150]
Hi, I am new, I try DeBug source code, log into my private server.
Always FAIL_VERSION_INVALID, none of them succeed.
I'm just debugging, I'm not changing any code.

Server error： tried to login with modified client!

**Comment by 0blu** [comment]
You have to disable StrictVersion check in realmd and Warden in mangosd.

**Comment by yjwcw** [comment]
Thanks, how do I modify the source code. I can't find it at all.
