### ISSUE TITLE
Eagle Eye does not display resource nodes on minimap

### ISSUE THREAD

**Issue by Resistofc** [WowLegacyCore/HermesProxy#151]
Server Everlook

Hermes Version: 2022-11-29

With the 1.12 Client and on Classic i can see Mining/Herb nodes on the minimap, when using eagle eye or far sight.

With Hermes Proxy i can't see them anymore. The minimap goes transparent and does not display anything besides the GatherMate points from my current location.

https://imgur.com/a/cVNKaZA

**Comment by Newfriendfromwinter** [comment]
Minimaps go black while using Eagle Eye.

**Comment by 0blu** [comment]
Is a client bug that we cannot fix.
It was fixed in 1.14.1.
