### ISSUE TITLE
Linking 4 or more items into chat forces log out.

### ISSUE THREAD

**Issue by NiceLikeTryce** [WowLegacyCore/HermesProxy#153]
**Describe the bug**
Linking 4 or more items into chat forces log out upon pressing Enter. 3 or less items does not do this.

**Game Server**
Everlook

**Hermes Proxy Version**
Version 2022-12-01 *official* 3.5.0

**Comment by 0blu** [comment]
What items did you try to post?
What language are you using? English?

**Comment by NiceLikeTryce** [comment]
**Items:**
[Regal Wizard Hat of Fiery Wrath]
[Embersilk Leggings of Healing]
[Azora's Will]
[Stone Hammer of the Boar]
[Harpyclaw Short Bow]

**Language:**
English

**Error Line:**
23:46:01 |  Error   | WorldClient     | C P<S | Socket Closed By GameWorldServer (header)

**Comment by Kbosso** [comment]
Happens to me aswell when i link more then 4 items.

**Comment by 0blu** [comment]
Okay, it appears to only happen on Everlook
