### ISSUE TITLE
Collision height is not recalculated on mount/dismount

### ISSUE THREAD

**Issue by insunaa** [WowLegacyCore/HermesProxy#16]
On 2.4.3 these calculations were probably done clientside, so there was no need to update collision height for player models.
With 2.5.x the client needs to be told the character's collision height explicitly every time that it changes.

Currently this leads to characters that log in while mounted never fitting through doorframes, even after dismounting, while characters that log in dismounted fitting through any doorframe, even when mounted.

I tend to believe that this is something that requires serverside intervention to get done *properly*.
CMaNGOS for example already has a `GetCollisionHeight()` function in `Unit.cpp` so we can already calculate that value, we just don't seem to be transmitting it yet (because the 2.4.3 client has no such opcode afaik)

We can fake it by hijacking the DISMOUNT and MOUNT CMSG/SMSGs and sending "sensible" default values. This will obviously not be perfect, but it should eliminate some trouble that currently occurs

**Comment by insunaa** [comment]
I tried implementing that but it's clear that I have no idea how to use C# or how to build WoW packets.
I managed to get the client to not crash when sending it these opcodes, but it didn't change anything about the collision at all.

Maybe I just sent the wrong data, I have no sniffs available to me aside from the ones posted in the hover/stealth issue

**Comment by ratkosrb** [comment]
Fixed in https://github.com/WowLegacyCore/HermesProxy/commit/2de29ff861bc6a5b636c18d10a1e7b886935444e
