### ISSUE TITLE
ignore doesnt work

### ISSUE THREAD

**Issue by chudmeister** [WowLegacyCore/HermesProxy#160]
when doing /ignore or even right click ignore for any player it doesnt work. whispers/trades/emotes still go through.

**Comment by Kbosso** [comment]
Can confirm

**Comment by 0blu** [comment]
In 1.12 the **client** handles the ignore.
In 1.14 the **server** handles the ignore.

Since Hermes currently does not handle the ignore, all messages are getting forwarded to the ModernClient.

**Comment by chudmeister** [comment]
ok makes sense, could there be a script made to facilitate ignore function for the moment?
