### ISSUE TITLE
[Vanilla] Can only choose neighbour flight points

### ISSUE THREAD

**Issue by palfibeni** [WowLegacyCore/HermesProxy#17]
When trying to flight further, hermes proxy throws the following error, and flying is not possible:
Trying to find from Western Plaugelands / Chillwind Camp to Arathi, Refugee pointe:
![image](https://user-images.githubusercontent.com/13693970/169996818-e1c94422-2fe0-44ad-aecd-de337bcb5296.png)

**Comment by ratkosrb** [comment]
The error in the picture is unrelated. It's about transport gameobjects (ships, zeppelins).

**Comment by palfibeni** [comment]
Oh right, there is no error, it was just coincidence that error occured.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/WowLegacyCore/HermesProxy/commit/8e72f33fb77a25a2fabd77c29c5cfac39c9e5d24
