### ISSUE TITLE
Unable to join Raid groups

### ISSUE THREAD

**Issue by fredsj94** [WowLegacyCore/HermesProxy#175]
Unable to join raidgroups on everlook, client keeps crashing during the stay in raid. Any solutions for this?

**Comment by 0blu** [comment]
- What Version are you using
- Can you provide some screenshots of the crash

**Comment by fredsj94** [comment]
Using the version from this YT link in desciption. I didnt think of taking any screenshots unfortunately

https://www.youtube.com/watch?v=H2sgtBIUigs&ab_channel=brotalnia

**Comment by 0blu** [comment]
Can you try the newer version https://github.com/WowLegacyCore/HermesProxy/releases

**Comment by fredsj94** [comment]
Alright, ill try new version - thanks for quick response
