### ISSUE TITLE
Random Hunter Pet Abandonment (Pet Disappears forever - can't call/revive says pet is gone)

### ISSUE THREAD

**Issue by dontwakedad** [WowLegacyCore/HermesProxy#176]
**Describe the bug**
After logging out / logging in, calling your pet can cause it to disappear as if you abandoned it. 
This has happened to users who has logged out for hours, as well as users who logged out/logged in instantly.
Here's a clip of it happening: https://youtu.be/3I2l-kdAtbo

**Game Server**
Everlook (Vanilla)

**Hermes Proxy Version**
Both the old version(11-29-22) and v3.5

**Comment by 0blu** [comment]
If this was Lupos I am sorry.

I can reproduce it by:
- Having a pet while mounted
- TP somewhere so pet gets removed
- Use `Call Pet` while being mounted (not possible in vanilla)
- Pet gone forever

**Comment by dontwakedad** [comment]
yeah it was 😭 I'm glad you were able to reproduce the issue though. 
For reference, I flew from Org to Desolace - this might have acted as the TP and then did the relog while mounted and call.

**Comment by Kbosso** [comment]
can confirm this bug, it happened to me aswell 2 hrs ago with my Brooken Tooth.

**Comment by 0blu** [comment]
Actually your pet is still in the db while not being replaced by a new one.
This is a vMangos bug.

**Comment by Kbosso** [comment]
> Actually your pet is still in the db while not being replaced by a new one. This is a vMangos bug.

Okay, so devs on the project i play (everlook) should be able to restore it you think?

**Comment by dontwakedad** [comment]
@0blu 
I'm not sure if this helps, but Wall's response 
![image](https://user-images.githubusercontent.com/71674830/205512017-6fc6169b-e91f-4ba3-992b-a7e1497a6132.png)

**Comment by Wall-core** [comment]
> > @0blu I'm not sure if this helps, but Wall's response ![image](https://user-images.githubusercontent.com/71674830/205512017-6fc6169b-e91f-4ba3-992b-a7e1497a6132.png)
> 
> awh okey.. Well yeah gonna reroll i think if they dont find a way to restore it.. Not very nice to play hunter and spend days taming and lvling the rare pets if they just gonna dissapear. Anyways much appriciation for your answer, and also id like to take the time to thank you for doing this project, its truly awesome and im loving playing on it,

just don't use 1.14 as a hunter, this issue doesn't happen with 1.12 client

**Comment by 0blu** [comment]
Please don't flame wall.
But @Wall-core it can be reproduced with a laggy 1.12 client that does not thing it's being mounted.
Just do `.cast 883` while being mounted simulate a client that invoked the pell.

**Comment by Kbosso** [comment]
> Please don't flame wall. But @Wall-core it can be reproduced with a laggy 1.12 client that does not think it's mounted. Just do `.cast 883` while being mounted simulate a client that invoked the spell.

i would never flame anyone mate! Thanks for the update.

**Comment by Kbosso** [comment]
> 

So theres no way you can get me my brooken tooth back?

**Comment by Wall-core** [comment]
> Please don't flame wall. But @Wall-core it can be reproduced with a laggy 1.12 client that does not think it's mounted. Just do `.cast 883` while being mounted simulate a client that invoked the spell.

lemme test real quick

**Comment by Kbosso** [comment]
*praying*

**Comment by Wall-core** [comment]
Yep was able to reproduce. I'll let Brotalnia know

**Comment by Kbosso** [comment]
> Yep was able to reproduce. I'll let Brotalnia know

Could u try reproduce my pet? Character is "Namens" in game, logged in right now.

**Comment by ratkosrb** [comment]
I've fixed the issue in vmangos.
https://github.com/vmangos/core/commit/ff7cf1fe4b12816e12c6a0a59f4de8002b1cc160

**Comment by Trsko** [comment]
Was hoping on better outcome on this thread, i had to run back to SFK and tame a slavering worg because of this, initially i thought i forgot to feed my pet but i know thats not the issue.

**Comment by zelazrgn** [comment]
@ratkosrb I just reproduced a different way of losing a pet, two people experienced it recently in mara.

https://youtu.be/Hjfo93o073I?t=111

I zoned in, spammed call pet, didn't lose it. Zoned out, spammed again, lost it. Similar to mount in that it shows up for a second then disappears.

**Comment by zelazrgn** [comment]
I also just reproduced it in a similar way by logging out, logging in, spamming call pet.

https://www.youtube.com/watch?v=MQAIag22Kls

**Comment by 0blu** [comment]
Please contact Wall if you play on Everlook.
It's a known bug and he most probably can restore your pets or has backups of it.
I mean it is very unlikely that a normal player would release a rare pet.
This is not an issue that we can resolve here.

**Comment by ratkosrb** [comment]
@zelazrgn You reproduced it on a freshly compiled vmangos after the fix, or on a private server that has not been updated with the fix yet?

**Comment by zelazrgn** [comment]
@ratkosrb Just on everlook within the last 30 mins, I was hoping someone who was familiar with compiling it could confirm. Hopefully the recent fix solves both.

It was also just as easy to reproduce the login case on 1.12.

**Comment by Wall-core** [comment]
It's fixed in vmangos and will be applied to Everlook on Wednesday (possibly sooner). Just hang tight, and keep your rare pets stabled until then.

**Comment by zelazrgn** [comment]
@Wall-core I just wanted to make sure we didn't need an extra fix, so looks likely don't need an additional fix for calling pet immediately after loading? (unrelated to mount)

**Comment by zelazrgn** [comment]
I attempted to reproduce the call pet spam on load screen bug on everlook after server restart and I'm no longer able to reproduce it!
