### ISSUE TITLE
Wrong error message inviting enemy player

### ISSUE THREAD

**Issue by Daribon** [WowLegacyCore/HermesProxy#178]
**Describe the bug**
If you use /invite on a horde player it currently gives you the error message:
ERR_NOT_LEADER = You are not the party leader.

It should give you the error:
GUILD_NOT_ALLIED_S = %s is not part of your alliance.
On 1.12.1 it says "Target is not part of your alliance.

**Game Server**
VMaNGOS

**Hermes Proxy Version**
![WindowsTerminal_kQPZSKj6tp](https://user-images.githubusercontent.com/6137576/205520151-6968f477-a034-4358-8c21-ba3dc4871604.png)

**Comment by 0blu** [comment]
Already fixed in latest release
