### ISSUE TITLE
Flying from OG - The crossroads (animation bugged out)

### ISSUE THREAD

**Issue by Kbosso** [WowLegacyCore/HermesProxy#179]
**Describe the bug**
Flying from OG -> Crossroads bugged out the animation. My char was just instantly telported to the FP in crossroads while still being on the flying mount. After the time that it takes to fly from OG to Barrens my character landed from the flying mount.

**Game Server**
Hermesproxy
Everlook (horde side)

Screenshot

Screenshot lost, will upload if it happens again.

**Comment by 0blu** [comment]
Will be tracked by #107
