### ISSUE TITLE
Linking +3 white items with text after dc's the client.

### ISSUE THREAD

**Issue by Kbosso** [WowLegacyCore/HermesProxy#186]
**Describe the bug**
When you link more then 3 items + put in a certain amount of text the client disconnects you. Abit alike were the client would disconnect you if you linked more then 4 green/blue items.

**Game Server**
Hermesproxy Release v3.6

**Hermes Proxy Version**
1.14

Posting this text dc's the client.

![image](https://user-images.githubusercontent.com/119659803/206055756-d7022870-4571-4e7c-ac5b-92f3e8b2ac1c.png)

https://gyazo.com/1a6b7dced4f8f89c2e130a5990976f19 (image link)

**Comment by Kbosso** [comment]
My bad, ofc im using the new version.

**Comment by Kbosso** [comment]
> There is no Hermesproxy 1.14. Use the Latest Version: https://github.com/WowLegacyCore/HermesProxy/releases

Should not be closed, im using the newest version and the bug is still there.

**Comment by 0blu** [comment]
I forgot to update the ChannelText handler.
Only extra long whisper and normal text messages are working.

**Comment by 0blu** [comment]
Should be fixed with version 3.7. If you are still experience this error please reopen the issue.
