### ISSUE TITLE
Can it be run in the ECS? My local link

### ISSUE THREAD

**Issue by danusha000** [WowLegacyCore/HermesProxy#193]
Can it be run in the ECS? My local link

**Comment by 0blu** [comment]
I'm not sure what you are trying to ask.
You can run HermesProxy in an AWS EC2 instance (ubuntu).
You have port forward the correct ports and change the `ExternalAddress` in your HermesProxy.conf

I'm closing it for now, if you are still experience this error please reopen the issue.
