### ISSUE TITLE
Can't link  green items

### ISSUE THREAD

**Issue by Kbosso** [WowLegacyCore/HermesProxy#197]
No idea why this started to happen just today but when ever i link 1 green item i get Dcd. Is it because of the zone im in? Strange bug. 

Server: Everlook

1.14 client 
Playing NE hunter lvl 49 in the zone Tanaris - more specificly "Dunemaul compound" 
No idea if that even mathers, gonna try to link the items in /say and /world in another zone and see if it changes anything.

items i cant link: Abdjurer's Hood of Shadow Wrath   - Chieftain's Boots of Agility

I've been able to link theese items before? No idea whats wrong tbh.

**Comment by Kbosso** [comment]
nevermind, this is due to the server

**Comment by bibibobob** [comment]
For me, when others link green items, it doesn't show the core  (+int, +stam, etc.) stats when I click on the item to view the stats.

**Comment by 0blu** [comment]
The dc bug was fixed in a recent release.

Stats are a client issue. We currently do not patch the stats of items.
