### ISSUE TITLE
[Vanilla] ships and zeppelins not appearing.

### ISSUE THREAD

**Issue by palfibeni** [WowLegacyCore/HermesProxy#20]
Following errors are thrown, and the zeppelins and transport ships not appear in the game, using the classic client.
```
ort/0 R0/S0 Map: 2560 Low: 5
14:31:47 | Error   | UpdateHandler | Broken create1 without position for Full: 0x18000140000000000000000000000000 Transport/0 R0/S0 Map: 2560 Low: 5
14:31:57 | Error   | UpdateHandler | Broken create1 without position for Full: 0x18000040000000000000000000000000 Transport/0 R0/S0 Map: 512 Low: 1
14:32:34 | Error   | UpdateHandler | Broken create1 without position for Full: 0x18000080000000000000000000000000 Transport/0 R0/S0 Map: 1024 Low: 2
```

**Comment by MaxtorCoder** [comment]
If I remember correctly transports are not implemented yet (?)

No idea for sure, let me double check

**Comment by ratkosrb** [comment]
Transports are implemented and should work. The problem you have is that this server does not actually use correct format. It's not sending the static gameobject position of the transport. Without it the transport can't work in new clients.

This flag must be set for transports and the stationary position should be given by server.
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Object/Object.cpp#L380
