### ISSUE TITLE
Leveling Addon Issue 

### ISSUE THREAD

**Issue by deaththegamer6** [WowLegacyCore/HermesProxy#204]
when moving to another continent ( kalimdor to eastern kingdom or vice versa) all completed quest show up again when using questie addon 

Game Server: SPP TBC 

Hermes Proxy Version: 3.6.0

**Comment by insunaa** [comment]
Current server software does not have an API / CMSG handler for requesting quest status. For this to work 100% as expected it would need the server to implement either custom opcodes or custom handlers to chat events. No server developer currently has any plans for this as it's completely outside of project scope.

If you have some C++ knowledge you can try to work on this yourself tho.

Sometime in 2023-2024 I'm going to implement the Threat API for Vanilla + TBC in CMaNGOS using specially crafted addon messages. The Questie issue could be solved similarly. Don't hold your breath for it tho, this has exceptionally low priority for people.

HermesProxy *does* keep a record of completed quests **I believe**, so while that won't be able to show you quests you've finished when not using HermesProxy, it'll show you quests as completed that you did with HermesProxy active.

See https://github.com/WowLegacyCore/HermesProxy#chat-commands for manual intervention in that regard

**Comment by 0blu** [comment]
It's probably in issue with how I implemented the quest flags.
When changing the continent the player is re-created but the quests are not sent.

**Comment by Skymanym** [comment]
> We do keep track of completed quests in the `AccountData` folder.
> 
> But it's probably an issue with how I implemented the CompletedQuest flags. When changing the continent the player is re-created but the quests are not sent.
> 
> https://github.com/WowLegacyCore/HermesProxy/blob/19beefe1c254197bc194c0066c03ae815395c1e9/HermesProxy/World/Client/PacketHandlers/UpdateHandler.cs#L121-L128

Hi, I got the same problem. Looks like as you said, when character getting "recreated", quest are not sent properly.
Reload is not working neither. I found only way to resend quests is logout and login again.
Is there any command line that I can use ingame to manually resend quests?
