### ISSUE TITLE
Buying out an item does not go away on the ah

### ISSUE THREAD

**Issue by Fearyii** [WowLegacyCore/HermesProxy#205]
**Describe the bug**
Action house Item does not go away after buying it out

Recreate: Buy an item from AH

**Game Server**
Everlook

**Hermes Proxy Version**
3.6.0 Winterspring

SS:
![image](https://user-images.githubusercontent.com/111935564/207952812-bb2d35cc-4a6f-4c1d-80aa-e3dbb8fe578a.png)

**Comment by Daribon** [comment]
Can confirm. I have the same issue.

**Comment by wodim** [comment]
I use aux and the AH is really buggy. It stops working after practically anything you do and you have to close and open the window.  Stacking when posting is wrong, auctions don't show after you post them... it's a mess.

**Comment by ratkosrb** [comment]
I think I've fixed the AH issues on my fork. You can find a compiled release in the description of my Youtube video to test it.
https://github.com/ratkosrb/HermesProxy/commit/2333e532661d19768e269c08f7b34e49645d8b29

**Comment by Fearyii** [comment]
> I think I've fixed the AH issues on my fork. You can find a compiled release in the description of my Youtube video to test it. [ratkosrb@2333e53](https://github.com/ratkosrb/HermesProxy/commit/2333e532661d19768e269c08f7b34e49645d8b29)

Is it possible to put it in the offical hermesproxy so i can compile it with the rest of the changes made by blu?

**Comment by 0blu** [comment]
I will make a new release at the beginning of next year

**Comment by wodim** [comment]
You should also be careful when posting stuff - if you try to post 3 stacks of 1 item at 1g each item you end up posting 1 stack of 3 items for 1g.

**Comment by bibibobob** [comment]
Same issue - Using Auctionator

**Comment by 0blu** [comment]
Was fixed in latest release (3.7)
