### ISSUE TITLE
iMorph with HermesProxy 

### ISSUE THREAD

**Issue by dontwakedad** [WowLegacyCore/HermesProxy#209]
**Bug**
iMorph for the 1.14 version works but Hermes Proxy crashes on any loading (such as hearth, /rl, instances, etc)
Attached the Crash Report of Hermes Proxy if it helps solve the issue at all.

**Game Server**
Everlook

**Hermes Proxy Version**
3.6.0

[iMorph-HermesProxyCrashReport.txt](https://github.com/WowLegacyCore/HermesProxy/files/10252210/iMorph-HermesProxyCrashReport.txt)

**Comment by MaxtorCoder** [comment]
No support for iMorph

**Comment by Fearyii** [comment]
> **Bug** iMorph for the 1.14 version works but Hermes Proxy crashes on any loading (such as hearth, /rl, instances, etc) Attached the Crash Report of Hermes Proxy if it helps solve the issue at all.
> 
> **Game Server** Everlook
> 
> **Hermes Proxy Version** 3.6.0
> 
> [iMorph-HermesProxyCrashReport.txt](https://github.com/WowLegacyCore/HermesProxy/files/10252210/iMorph-HermesProxyCrashReport.txt)

Currently i am using imorph and i am not having any problems and running it perfectly fine using almost everything it offers probably an imorph problem if ur using the 1.14.1 (im on 1.14.0)

**Comment by dontwakedad** [comment]
> > **Bug** iMorph for the 1.14 version works but Hermes Proxy crashes on any loading (such as hearth, /rl, instances, etc) Attached the Crash Report of Hermes Proxy if it helps solve the issue at all.
> > **Game Server** Everlook
> > **Hermes Proxy Version** 3.6.0
> > [iMorph-HermesProxyCrashReport.txt](https://github.com/WowLegacyCore/HermesProxy/files/10252210/iMorph-HermesProxyCrashReport.txt)
> 
> Currently i am using imorph and i am not having any problems and running it perfectly fine using almost everything it offers probably an imorph problem if ur using the 1.14.1 (im on 1.14.0)
> 
> Also i don't think hermes has anything to do with that since imorph is completly client side

I'm on 1.14 as well.. are you using 1.14.0.40618?
