### ISSUE TITLE
After using Eyes of the Beast, character stuck

### ISSUE THREAD

**Issue by xicyboy** [WowLegacyCore/HermesProxy#212]
I can't move after i use the hunter's spell "eyes of the beast" in combat.

Game Server
Everlook

Hermes Proxy Version
![image](https://user-images.githubusercontent.com/119513377/208940598-b6f85975-5ca1-488b-bb32-653a324f067f.png)

video https://youtu.be/YzqRLpzyXcc

**Comment by zyfei** [comment]
you can try this 
https://github.com/zyfei/HermesProxy-heitu
fixed some issues
