### ISSUE TITLE
when does the hermesproxy support 2FA

### ISSUE THREAD

**Issue by xicyboy** [WowLegacyCore/HermesProxy#218]
when does the hermesproxy support 2FA

when i was playing on everlook, i'm enabled 2FA, when did the hermesproxy support 2FA,or no plan。 

**Game Server**
Everlook

**Hermes Proxy Version**
v3.6

**Comment by insunaa** [comment]
Pretty sure the 2FA protocol hasn't been successfully reversed yet. I've looked into it in the past but I hit a dead end. Don't hold your breath for it, it's not easy to figure out and it's not exactly critical.

**Comment by 0blu** [comment]
Will be tracked by #66
