### ISSUE TITLE
Flight path bug

### ISSUE THREAD

**Issue by dstplz** [WowLegacyCore/HermesProxy#221]
**Flight paths are bugged. When i try to fly from point A to point B. I just end up teleporting to the spot i wanted to fly to and then sit on the wyvern at the spot i wanted to fly to until i have magically arrived there in the timespan it would take for me to fly there. Really strange.**

**Everlook**

**Version 2022-12-04 *official* 3.6.0**

**Comment by 0blu** [comment]
Will be tracked by #107
