### ISSUE TITLE
[Classic] Fly hack

### ISSUE THREAD

**Issue by sh3ppard** [WowLegacyCore/HermesProxy#231]
**Describe the bug**
When you flight on gryphon/wyvern and battleground queue popped (WSG) then after join on battleground you can't move at all and character model hovering above the ground. After restart the client you can fly (actually swimming animation) on battleground like in this [video](https://www.youtube.com/watch?v=ieuWIbvX0As&ab_channel=StimmerShow).

**Game Server**
Everlook

**Hermes Proxy Version**
3.6

**Comment by 0blu** [comment]
I think this was a bug with the server software itself (vMangos) that was recently fixed.
