### ISSUE TITLE
[Classic] Incorrect text display for teachers

### ISSUE THREAD

**Issue by WLMeow** [WowLegacyCore/HermesProxy#238]
**Incorrect text display for teachers**
https://www.wowhead.com/classic/npc=3357/makaru
https://www.wowhead.com/classic/npc=11017/roxxik
https://www.wowhead.com/classic/npc=3412/nogg
https://www.wowhead.com/classic/npc=3355/saru-steelfury
https://www.wowhead.com/classic/npc=3354/sorek
https://www.wowhead.com/classic/npc=3408/zelmak
https://www.wowhead.com/classic/npc=3353/grezz-ragefist
etc.
If necessary, the list continues.

![image](https://user-images.githubusercontent.com/122168101/212673727-51d91b32-c9b9-452a-abea-6b5fa2becaa1.png)

Server: Warcraft Life
![image](https://user-images.githubusercontent.com/122168101/212677270-e7257619-cc81-4401-b167-a088f5847c46.png)

**Comment by ratkosrb** [comment]
Have you tested with 1.12 too? It could be that the server has garbled locale tables.
