### ISSUE TITLE
[Classic] Incorrect display of the color of the "shaman" class

### ISSUE THREAD

**Issue by WLMeow** [WowLegacyCore/HermesProxy#239]
Shaman class color is pink instead of dark blue.
![image](https://user-images.githubusercontent.com/122168101/212768269-3806e5b1-93d4-4522-a983-2b41122ea82c.png)
Server: Warcraft Life
![image](https://user-images.githubusercontent.com/122168101/212768338-d5a7ab6e-e65c-4e2e-bf22-75b7d68bdd00.png)

**Comment by 0blu** [comment]
This is actually not a bug from HermesProxy.
In 1.12 / classic shamans were pink <.<
It was changed in TBC.

**Comment by WLMeow** [comment]
Paladins and shamans get the same color (pink) , right?

**Comment by WLMeow** [comment]
Sorry, I didn't know it.
