### ISSUE TITLE
Usage Instructions Improvements

### ISSUE THREAD

**Issue by John-Ivar-Flatmo** [WowLegacyCore/HermesProxy#241]
continuation of https://github.com/WowLegacyCore/HermesProxy/issues/235 witch was closed without resolving nor marking as will not do(or similar).

Improved in file instructions and/or create instructions in readme regarding accountData

Separation of instructions for users and hosts, to allow for simpler user(just wants to connect to a server) instructions and more in depth host(wants to allow clients to connect without running a local hermesproxy server) information

Explanation of clientSeed, or removal of clientSeed dependency if not required.

**Comment by 0blu** [comment]
I have 2 question that you need to answer before you create a new comment:
- Did you even try to execute HermesProxy once?
- Did you try to launch the client without the static seed?

The `AccountData` is initially empty / not there. The folder is **automatically created** and filled up with data as you play.
*To be fair I'm going to update the included `.txt` files in the next release, to tell the user that they only need to copy this folder if you are upgrading from a newer version.*

As explained in the referenced issue the `StaticSeed` is there so the modified client can communicate with HermesProxy.
Try to connect without a static seed and see what happens.

Currently HermesProxy requires a bit of knowledge on how to modify the config file.
Which is not optimal, maybe we will have a dedicated launcher Gui in the far future.
The normal user usaually just has to change 2 things:
- change the `SET portal "127.0.0.1"` in `<wow>/WTF/Config.wtf`
- and change the `ServerAddress` in Hermes's config
https://github.com/WowLegacyCore/HermesProxy/blob/9ef565fafb6e95d4f9dab9581f985f409d9b505c/HermesProxy/HermesProxy.config#L24-L30

If you want to host HermesProxy for other players you should know how to read and modify a config file.
A good start is to modify the `ExternalAddress`.
https://github.com/WowLegacyCore/HermesProxy/blob/9ef565fafb6e95d4f9dab9581f985f409d9b505c/HermesProxy/HermesProxy.config#L49-L54

**Comment by John-Ivar-Flatmo** [comment]
> I have 2 question that you need to answer before you create a new comment:
> 
>     * Did you even try to execute HermesProxy once?
> 
>     * Did you try to launch the client without the static seed?
> 
> 
> The `AccountData` is initially empty / not there. The folder is **automatically created** and filled up with data as you play. _To be fair I'm going to update the included `.txt` files in the next release, to tell the user that they only need to copy this folder if you are upgrading from a newer version._
> 
> As explained in the referenced issue the `StaticSeed` is there so the modified client can communicate with HermesProxy. Try to connect without a static seed and see what happens.
> 
> Currently HermesProxy requires a bit of knowledge on how to modify the config file. Which is not optimal, maybe we will have a dedicated launcher Gui in the far future. The normal user usaually just has to change 2 things:
> 
>     * change the `SET portal "127.0.0.1"` in `<wow>/WTF/Config.wtf`
> 
>     * and change the `ServerAddress` in Hermes's config
>       https://github.com/WowLegacyCore/HermesProxy/blob/9ef565fafb6e95d4f9dab9581f985f409d9b505c/HermesProxy/HermesProxy.config#L24-L30
> 
> 
> If you want to host HermesProxy for other players you should know how to read and modify a config file. A good start is to modify the `ExternalAddress`.
> 
> https://github.com/WowLegacyCore/HermesProxy/blob/9ef565fafb6e95d4f9dab9581f985f409d9b505c/HermesProxy/HermesProxy.config#L49-L54


Just posting this to clarify, i will not be responding to further messages/comments as i am clearly not wanted here.
the issue i had with hermesproxy was resolved shortly after opening the first github issue, it was simply a dns resolution problem, witch i saw had been closed on here and thus i falsely assumed it had been fixed.

yes i executed hermesproxy
yes i tried launching with and without static seed, note my Arctium launcher had a memory access issue on login when ran thugh wine(i am on linux), being the host rather than i player i did not spend significant time attempting to resolve this.

and i still have not(i went and looked for it in my hermesproxy server setup and its there now but it only generates after an account is actualy playing(or connected not entirely sure), witch meens i had no way of knowing this folder exsisted  nor seing it untill anyone else connected since i never played on a modern client) seen a accountData folder, it possible this is because i never played on a modern client, other people did
nor do i know why hermesproxy requires the static seed, i can only assume, so i think its required by the modern clients.

i was posting because i had a suggestion for improvement not because i needed help.
i don't know why anyone thought that, infact i used the informal language to indicate that i was not a "noob" specifically so that this would not happen, clearly i did a poor job and for that i can only apologize.
perhaps some better tag options should be added to avoid misinterpreting the intentions of the person opening the issue.

i think its important you(all) know i will not be posting any more github issues at the very least not anything related to this because all the arguing is something i do not have time for.
I recommend in future that you(all) do not resist changes/suggestions so actively and in sutch  a hostile(referring to the lack of respect for the original opened issue, the improper parsing(by those who commented wrongly assuming i needed help) of my initial issue's text, the closing of the issue as "too heated") manner as to not drive away those only wishing to help.

Only hoping to clarify this so that you(all) may learn from this, i will likely not read any comments, i will also not respond to any comments, mainly because im not here with any opinions rather simple hard facts, and i have no intention of arguing further as i do not enjoy it nor believe that this is the place for it,  im out have a nice day.
