### ISSUE TITLE
Not able to leave Battleground queue

### ISSUE THREAD

**Issue by fixurshit** [WowLegacyCore/HermesProxy#252]
When you right-click the icon the option to leave the queue is greyed out.
![bgqueue](https://user-images.githubusercontent.com/121209911/215630481-3299f620-bbbf-4143-b012-f8961dd01b82.png)

**Comment by Daribon** [comment]
Client issue of 1.14.0. Blizzard did not have it working in that patch.

It works on on 1.14.1 and above

**Comment by sh3ppard** [comment]
You can use trick for it: you should be leader of group.
