### ISSUE TITLE
zepplin

### ISSUE THREAD

**Issue by razorslack** [WowLegacyCore/HermesProxy#256]
Zepplin is bugged horde side client 1.14.0

**Comment by 0blu** [comment]
Already tracked by #200 I guess.

**Comment by razorslack** [comment]
no cant see the zep 
when other players enter zep they disappear

**Comment by 0blu** [comment]
Which zeppelin are you talking about?

**Comment by razorslack** [comment]
the zepplin dont appear anywhere
________________________________
Fra: _BLU ***@***.***>
Sendt: 4. februar 2023 20:40
Til: WowLegacyCore/HermesProxy ***@***.***>
Cc: razorslack ***@***.***>; Author ***@***.***>
Emne: Re: [WowLegacyCore/HermesProxy] zepplin (Issue #256)


Which zeppelin are you talking about?

**Comment by 0blu** [comment]
On what server are you playing?

**Comment by razorslack** [comment]
Moonwell
________________________________
Fra: _BLU ***@***.***>
Sendt: 6. februar 2023 07:27
Til: WowLegacyCore/HermesProxy ***@***.***>
Cc: razorslack ***@***.***>; Author ***@***.***>
Emne: Re: [WowLegacyCore/HermesProxy] zepplin (Issue #256)


On what server are you playing?

**Comment by razorslack** [comment]
sorry Elysium where the zepplin is bugged

________________________________
Fra: _BLU ***@***.***>
Sendt: 6. februar 2023 07:27
Til: WowLegacyCore/HermesProxy ***@***.***>
Cc: razorslack ***@***.***>; Author ***@***.***>
Emne: Re: [WowLegacyCore/HermesProxy] zepplin (Issue #256)


On what server are you playing?
