### ISSUE TITLE
tbc

### ISSUE THREAD

**Issue by razorslack** [WowLegacyCore/HermesProxy#258]
hi can't get this working on with tbc tried both client 2.5.2 and 2,5,3
did the same as i am using on 1.14.0 client

**Comment by razorslack** [comment]
Unable to validate game version
<add key="ServerAddress" value="login.moonwell.su" /> right ?

**Comment by razorslack** [comment]
<add key="ServerAddress" value="server i am playing" />

**Comment by razorslack** [comment]
add key="ServerAddress" value="login.moonwell.su"

**Comment by 0blu** [comment]
![image](https://user-images.githubusercontent.com/7039020/217032844-62dbf480-da66-4c49-8ac9-bec2a3e8687e.png)
