### ISSUE TITLE
i want play on my macbook，but how should i do？

### ISSUE THREAD

**Issue by xicyboy** [WowLegacyCore/HermesProxy#261]
i want play on my macbook，I download this app and wow mac
but i can't play nowhow should i do to play？
![image](https://user-images.githubusercontent.com/119513377/217530842-25b4fea5-9f2d-4d28-898a-8719140c9ee4.png)

**Comment by henhouse** [comment]
@xicyboy I think you're looking for this: https://github.com/0blu/WinterspringLauncher/releases

**Comment by xicyboy** [comment]
great,bro

> @xicyboy I think you're looking for this: https://github.com/0blu/WinterspringLauncher/releases

**Comment by 0blu** [comment]
Will be tracked by #78
