### ISSUE TITLE
Doesn't support queue to login?

### ISSUE THREAD

**Issue by sh3ppard** [WowLegacyCore/HermesProxy#267]
**Describe the bug**
Looks like hermes doesn't support queue if server has it.

**Game Server**
Everlook 1.12

**Hermes Proxy Version**
3.7

**Comment by sh3ppard** [comment]
[Brotalnia implemented](https://github.com/ratkosrb/HermesProxy/commit/f8d71e92d6f78e0a255ab56eb5be7a618c840bfa) queue support. So need to do pull request.

**Comment by 0blu** [comment]
I don't know if the proposed fix is gonna work.
If I test it on my local server I get disconnected after a while in queue.

**Comment by ratkosrb** [comment]
It worked for me.

**Comment by AlphaBril** [comment]
@ratkosrb Can you explain to me how to implement Brotalnia solution ? cloned his project and successfully done a build, but the released binary is only 265ko in size vs 24347ko for the official release.

**Comment by sh3ppard** [comment]
@AlphaBril you can't just build and play on everlook.
> everlook has both strict version checking enabled and warden
> you cant connect if you compile the proxy yourself, because the emulation code for this in hermesproxy is kept private, because it could be used in bots, its too dangerous to publish
> so only the version of the proxy compiled by me and blu can connect to servers with those security features enabled

**Comment by AlphaBril** [comment]
okay so I just have to wait that hopefully the queue fix will be merged ?

**Comment by sh3ppard** [comment]
@AlphaBril yes
