### ISSUE TITLE
How to play on two clients?

### ISSUE THREAD

**Issue by noobax** [WowLegacyCore/HermesProxy#269]
When I launch a second client to play on an other account I'm unable to connect

I tried to start a second Hermes server with a different ExternalAddress but did not work

Anyone has an idea what I could do?

**Comment by 0blu** [comment]
It should work. One HermesProxy instance can support multiple game clients at the same time.
You dont have to change the ExternalAddress for this.
Maybe the server you are playing on does not allow two connections from the same ip.
