### ISSUE TITLE
Cant enter world on TBC

### ISSUE THREAD

**Issue by Fearyii** [WowLegacyCore/HermesProxy#271]
**Describe the bug**
Black Character screen as shown below, can't enter world but can make character

**Game Server**
Stormforge TBC PTR

**Hermes Proxy Version**
3.7.0

SS: 
![image](https://user-images.githubusercontent.com/111935564/220461832-d1845f18-2060-4413-a037-e781b16687bb.png)

Hermes Log:
![image](https://user-images.githubusercontent.com/111935564/220461875-b1c9380d-06f9-48dd-ac2a-a4c17e2ce22c.png)

**Comment by ratkosrb** [comment]
Is this a closed ptr or available to the public?

**Comment by Fearyii** [comment]
> Is this a closed ptr or available to the public?

It was made public yesterday everyone can connect to it, also after a few tries it sometimes put me in the character screen its weird sometimes it works sometimes it does not

**Comment by MaxtorCoder** [comment]
What client version are you using?

**Comment by Fearyii** [comment]
> What client version are you using?

2.5.3, but as i mentioned above sometimes it gives this black screen sometimes it does not

**Comment by Arctic-Husky** [comment]
I'm on the same boat as you, but mine never loads the characters and the console doesn't show as many warnings, and also I get an error
![image](https://user-images.githubusercontent.com/1398269/220631513-dae667f0-d6f1-4199-90cd-8076f9a415f1.png)

**Comment by Fearyii** [comment]
> I'm on the same boat as you, same client version, proxy version, but mine never loads the characters and the console doesn't show as many warnings, and also I get an error ![image](https://user-images.githubusercontent.com/1398269/220631513-dae667f0-d6f1-4199-90cd-8076f9a415f1.png)

I just tried to log in and got the same problem i clicked on change realm clicked the PTR again and it loaded my characters now, so idk what is the problem just keep on trying and u will see the characters

**Comment by Arctic-Husky** [comment]
> > I'm on the same boat as you, same client version, proxy version, but mine never loads the characters and the console doesn't show as many warnings, and also I get an error ![image](https://user-images.githubusercontent.com/1398269/220631513-dae667f0-d6f1-4199-90cd-8076f9a415f1.png)
> 
> I just tried to log in and got the same problem i clicked on change realm clicked the PTR again and it loaded my characters now, so idk what is the problem just keep on trying and u will see the characters

Kept trying this but didn't work, weird

**Comment by clanat01** [comment]
@Arctic-Husky Just logged in to Stormforge PTR with 2.5.3 client. Initially you will see black screen on characters screen. Just click "Change Realm" button and select it again and you will get character creation screen. Don't forget to change build number in Hermes Proxy config file to use 2.5.3 client.
