### ISSUE TITLE
Warrior Overpower spell is usable without proc

### ISSUE THREAD

**Issue by Lihvar** [WowLegacyCore/HermesProxy#278]
**Describe the bug**
Warriors can use Overpower without the proc of enemy dodging the attack first.
Tested on 1.14.0 and 1.14.2 (Tested on 1.12.1 as well to make sure it's not a server issue and it's not)

**Game Server**
Local server based on latest cmangos core

**Hermes Proxy Version**
HermesProxy version 3.7.0

https://user-images.githubusercontent.com/33036901/221408339-486801f1-31e1-4dc0-b2ab-96d51923a91d.mp4

**Comment by ratkosrb** [comment]
That's a bug in the server core. It should not allow you to cast the spell.
