### ISSUE TITLE
Excuse me, is ClassicThreatMeter+KTM ready

### ISSUE THREAD

**Issue by sileagj** [WowLegacyCore/HermesProxy#281]
Excuse me, is ClassicThreatMeter+KTM ready

**Comment by MaxtorCoder** [comment]
Please ask in the discord

**Comment by Fearyii** [comment]
> Excuse me, is ClassicThreatMeter+KTM ready

creator of KTM for 1.12 made a compatible one for 1.14 that shows threat on all clients.

[KTMClassic](https://github.com/zelazrgn/KTMClassic)
