### ISSUE TITLE
Character freeze after hunter Eyes of the Beast control end.

### ISSUE THREAD

**Issue by coolzoom** [WowLegacyCore/HermesProxy#290]
**Describe the bug**

step to reproduce
1, cast hunter beast eye
2, control the pet to move as far as possible away from the player
3, when the cast bar disappears, the camera returns to the player but the player can not move.

tested this does not happen if the pet is within about 150 yard away from player
it is possible the Player::ModPossessPet does not reset player state correctly when the pet runs out of the visiblity range?
added some more info: 1.12 client is correct.

**Game Server**
vmangos latest, client 1.14.2

**Hermes Proxy Version**

3.7

**Comment by zyfei** [comment]
you can try this 
https://github.com/zyfei/HermesProxy-heitu
fixed some issues

**Comment by coolzoom** [comment]
> you can try this https://github.com/zyfei/HermesProxy-heitu fixed some issues

as bro mentioned, this is not the correct fix that still has a potential problem, there is a better fix currently ongoing. will remain this to be opened until that.
