### ISSUE TITLE
How to write a file that supports remote reading of HermesProxy.config and CSV directory files

### ISSUE THREAD

**Issue by 127y** [WowLegacyCore/HermesProxy#295]
How to write a file that supports remote reading of HermesProxy.config and CSV directory files

The source code itself does not support

For example, HermesProxy.config, I think 

http://www.xxx.com/HermesProxy/HermesProxy.config

http://www.xxx.com/HermesProxy/CSV/

**Comment by MaxtorCoder** [comment]
As you said yourself, code does not support it.
