### ISSUE TITLE
Finished quest icons doesn't show on minimap

### ISSUE THREAD

**Issue by redholm** [WowLegacyCore/HermesProxy#297]
_Remove all placeholder texts including this message here._

**Describe the bug**
The yellow round dots which normally displays on the minimap when a nearby quest can be turned in doesn't display.

**Game Server**
Latest compile of Vmangos core.

**Hermes Proxy Version**
Latest version of hermes.

**Comment by ratkosrb** [comment]
This should be fixed by https://github.com/WowLegacyCore/HermesProxy/commit/c2a8237b3d5a452852ba9a9349e776aeb5678104
