### ISSUE TITLE
Error UpdateHandler | Broken create1 without position for Transport Object

### ISSUE THREAD

**Issue by jackycyp** [WowLegacyCore/HermesProxy#298]
_Remove all placeholder texts including this message here._

**Describe the bug**
23:52:55 |  Warning | WorldClient     | C P<S | No handler for opcode SMSG_SPELL_MISS_LOG (587) (Got unknown packet from WorldServer)
23:52:55 |  Warning | WorldClient     | C P<S | No handler for opcode SMSG_SPELL_MISS_LOG (587) (Got unknown packet from WorldServer)
23:52:55 |  Warning | WorldClient     | C P<S | No handler for opcode SMSG_SPELL_MISS_LOG (587) (Got unknown packet from WorldServer)
23:52:55 |  Warning | WorldClient     | C P<S | No handler for opcode SMSG_SPELL_MISS_LOG (587) (Got unknown packet from WorldServer)
23:52:55 |  Warning | WorldClient     | C P<S | No handler for opcode SMSG_SPELL_MISS_LOG (587) (Got unknown packet from WorldServer)
23:52:55 |  Warning | WorldClient     | C P<S | No handler for opcode SMSG_SET_REST_START (542) (Got unknown packet from WorldServer)
23:52:55 |  Error   | UpdateHandler   | Broken create1 without position for Full: 0x18000040000000000000000000000000 Transport/0 R0/S0 Map: 512 Low: 1
23:52:55 |  Error   | UpdateHandler   | Broken create1 without position for Full: 0x18000080000000000000000000000000 Transport/0 R0/S0 Map: 1024 Low: 2
23:52:55 |  Error   | UpdateHandler   | Broken create1 without position for Full: 0x180001C0000000000000000000000000 Transport/0 R0/S0 Map: 3584 Low: 7
23:52:55 |  Error   | UpdateHandler   | Broken create1 without position for Full: 0x18000140000000000000000000000000 Transport/0 R0/S0 Map: 2560 Low: 5
23:52:55 |  Error   | UpdateHandler   | Broken create1 without position for Full: 0x18000100000000000000000000000000 Tra
**Game Server**
The server / emulator that you experienced this bug on.MANGOS 

**Hermes Proxy Version** 3.7
Tell us what version of Hermes Proxy you are using.
You can find this information at the start of Hermes Proxy:

I don't know what can I do to eliminate the problem!!

**Comment by 0blu** [comment]
On what server are you playing and on what version of the game (vanilla or tbc)?
I when I remember correctly I saw similar errors when playing TBC.

**Comment by jackycyp** [comment]
VANILLA 1.12

CLIENT  1.14

**Comment by 0blu** [comment]
Can you always reproduce it, or was that a one time thing?
Where in the gameworld did this occur?
On what server are you playing or if it's your local one: what mangos version do you use?

**Comment by jackycyp** [comment]
My local sever :VMaNGOS Repack by brotalnia   

This problem occurs every time I open the client, no matter what region my character is,but everything seems normal in the game except for the abandoned quest that cannot be retrieved."

**Comment by ratkosrb** [comment]
Are you using an ancient version of the repack? Because the transport errors should not happen in the newest version. Transport handling was refactored in like 2021.

**Comment by jackycyp** [comment]
Thanks !!that maybe is the problem,I am using the oldversion,I will try the newest version!thanks again!!!

**Comment by jackycyp** [comment]
IT worked!!THANKS for your patience!!
