### ISSUE TITLE
Deeprun Tram wrong direction on vMangos

### ISSUE THREAD

**Issue by 0blu** [WowLegacyCore/HermesProxy#31]
Is this related to vMangos or Hermes Proxy?
https://www.youtube.com/watch?v=uflKw2aZkME

**Comment by ratkosrb** [comment]
Yes I've seen that issue myself. Don't know why it works on 1.12 but not with new client, yet other elevators are fine. (the tram is an elevator)

**Comment by 0blu** [comment]
Unfortunately I don't have a model- / resourceviewer for classic.
Could it be the case that they changed the transport data in the client?
But somehow this does not make sense because 1 of the trains in each track is correct...

**Comment by Mige5** [comment]
I think fixing this might also fix the horizontal movement not working in the right direction with telredor elevator.

**Comment by 0blu** [comment]
In the Classic data the Carts have an inverted Animation.

I tried to Hotfix this but this resulted in the trains being mirrored. As soon as you stand on it, all other players see you in the other side of the cart.

I think the only option is to modify the GameObject Create/Read method and invert the rotation there.
