### ISSUE TITLE
Getting disconnected before character selection screen

### ISSUE THREAD

**Issue by kalypto89** [WowLegacyCore/HermesProxy#325]
I had a query unsure if its from hermes proxy or arctium launcher, my dev skills are inexistent.
Issue: 
I keep getting disconnected after I try to connect to the realm in the main menu
Server: everlook/smolderforge/henhouse)
I can get past the password authentication and select realm but it does not connect to character selection menu- server then throws me off. I have done the correct setup of arctium launcher and proxy (afaik) but this thing is persisting.
Hermes proxy version:  v3.7|Release v3.7 (2023-01-30)
Arctium launcher version: latest|Launcher Signed (2022/11/18)
![image_2023-07-11_130058489](https://github.com/WowLegacyCore/HermesProxy/assets/116260914/060aa0f6-6b6d-4b51-9d8e-7126b934bbdd)
![image](https://github.com/WowLegacyCore/HermesProxy/assets/116260914/8c6d3e8a-1ac6-4b5e-932c-f83210e5bceb)
![image](https://github.com/WowLegacyCore/HermesProxy/assets/116260914/e118321e-25ca-4f99-a510-4f8522963b05)
![image](https://github.com/WowLegacyCore/HermesProxy/assets/116260914/3691ebf3-5873-460c-8f7e-9b50923aa4c5)
![image](https://github.com/WowLegacyCore/HermesProxy/assets/116260914/381ff188-8e25-418c-959f-30165e1d2e8d)
![image](https://github.com/WowLegacyCore/HermesProxy/assets/116260914/aa4bef7e-0f8c-4f53-80b8-e7e12f3046fd)
![image](https://github.com/WowLegacyCore/HermesProxy/assets/116260914/eceff533-b1f3-4aac-a34d-bbb4e52b118d)
![image](https://github.com/WowLegacyCore/HermesProxy/assets/116260914/56da7486-60e7-477e-af1d-756dbc15eee1)

**Comment by kalypto89** [comment]
![image](https://github.com/WowLegacyCore/HermesProxy/assets/116260914/11464fa5-a493-4efa-8b17-898604a90600)

**Comment by 0blu** [comment]
Thank you for your detailed report. :)
Were you able to see the realmlist?

**Comment by ratkosrb** [comment]
Whenever you see this:

`WorldSocket.HandleAuthSession: Authentication failed for account`

It means you are not using the correct auth seed. If you are not going to use the **staticseed** option in the launcher, then you need to update the Hermes config with the real auth seed for this client version after reverse engineering it.

**Comment by kalypto89** [comment]
heya, thanks alot @0blu , adding --staticseed worked. guess i skipped this step in the setup i did. thanks alot!

**Comment by iferalplay** [comment]
I have same problem on sever smolderforge 2.4.3.I'm already adding --staticseed.

**Comment by henhouse** [comment]
> I have same problem on sever smolderforge 2.4.3.I'm already adding --staticseed.

Hi @iferalplay, sadly I don't support the HermesProxy on Smolderforge, so the system will disconnect you.

We have a _lot_ of custom items on there, and none of them will render or load in correctly with the modern client, so at this time it's not supported. Would love to one day, though.

**Comment by iferalplay** [comment]
got it,thx @henhouse
