### ISSUE TITLE
Possible to use 1.14.3 client?

### ISSUE THREAD

**Issue by SageBage** [WowLegacyCore/HermesProxy#329]
Sorry if this is the wrong section to post, but I couldn't find anywhere else. 
Like the title says, is it possible to use 1.14.3 client? Will Hermesproxy be updated so it works with the upcoming 1.14.4 Era Client? 

Thank you so much for this software, btw. It has been great getting to use the modern wow client for vanilla!

**Comment by MaxtorCoder** [comment]
Most likely not.

**Comment by Artur91425** [comment]
@SageBage  try this)
https://github.com/celguar/HermesProxy/releases

**Comment by SageBage** [comment]
@Artur91425 Unfortunately didn't work :/
![Skjermbilde 2023-09-08 080446](https://github.com/WowLegacyCore/HermesProxy/assets/141590515/730a92bb-8e65-45e9-b31d-f5d9a7e12d5a)
