### ISSUE TITLE
Becoming cc'd while changing warr stances

### ISSUE THREAD

**Issue by reetarded** [WowLegacyCore/HermesProxy#33]
Had a bug where I changed from battle to berserker stance and got cc'd right as I did, but I was in berserker stance but still had my battle stance bar with all of my battle stance abilities instead of my berserker rage abilities. 

I don't know if it is because of my relatively high ping (150+ from na).

**Comment by 0blu** [comment]
Might be fixed in one of newer releases.
If you are still experience this error please reopen the issue.
