### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by Gilleeuy** [WowLegacyCore/HermesProxy#330]
17:35:01 |  Server  | Server          | Starting Hermes Proxy...
17:35:01 |  Server  | Server          | Version 2023-06-04 *official* 3.8.0
17:35:01 |  Server  | Server          | Modern (Client) Build: V1_14_0_40618
17:35:01 |  Server  | Server          | Legacy (Server) Build: V1_12_1_5875
17:35:01 |  Storage | GameData        | Loading data files...
17:35:01 |  Server  | VersionChecker  | Loaded 833 legacy opcodes.
17:35:01 |  Server  | VersionChecker  | Loaded 1639 modern opcodes.
17:35:01 |  Storage | GameData        | Finished loading data.
17:35:01 |  Network | Server          | External IP: 127.0.0.1
17:35:01 |  Server  | Server          | Starting BnetTcpSession service on 127.0.0.1:1119...
17:35:01 |  Network | NetworkThread   | Network Thread Starting
17:35:01 |  Server  | Server          | Starting BnetRestApiSession service on 127.0.0.1:8081...
17:35:01 |  Network | NetworkThread   | Network Thread Starting
17:35:02 |  Server  | Server          | Starting RealmSocket service on 127.0.0.1:8084...
17:35:02 |  Network | NetworkThread   | Network Thread Starting
17:35:02 |  Server  | Server          | Starting WorldSocket service on 127.0.0.1:8086...
17:35:02 |  Network | NetworkThread   | Network Thread Starting
17:35:20 |  Server  | BnetTcpSession  | Accepting connection from 127.0.0.1:55607.
17:35:21 |  Error   | BnetServices    | [BnetTcp][127.0.0.1:55607] Battlenet.LogonRequest: Attempted to log in with wrong game version (using 49821)!

**Comment by ratkosrb** [comment]
The client you are using is not the expected version.

**Comment by LaurCzT** [comment]
You need to download one of the following wow classic versions:
1.14.0 (40618)
1.14.1 (41794)
1.14.2 (42597)
