### ISSUE TITLE
MacOS can't running....

### ISSUE THREAD

**Issue by Se7enJoy** [WowLegacyCore/HermesProxy#348]
Have a bug report:
 Unable to patch '/Users/xxxxx/WinterspringLauncher/hermes-proxy/CSV/Hotfix/ItemEffect1.csv' (WinterspringLauncher.HermesDataPatches.Hotfix.ItemEffect1.csv)

**Comment by 0blu** [comment]
Issue is related to WinterspringLauncher, discussions will be held there.
https://github.com/0blu/WinterspringLauncher/issues/42
