### ISSUE TITLE
the recently updated Arctium, can link to HermesProxy, but cannot log in to the account normally.

### ISSUE THREAD

**Issue by howarduong** [WowLegacyCore/HermesProxy#38]
I don't know why, I compiled the latest Arctium code, the recently updated Arctium, can link to HermesProxy, but cannot log in to the account normally. I do not know why.
The link file package provided on YouTube, Arctium has nearly 200 files, it is very messy, I downloaded the new standalone Arctium and can't log in to the account.

**Comment by ratkosrb** [comment]
You are using the wrong version of the launcher. You need the static auth seed branch. Unfortunately @Fabi has not provided a release for that version. The normal launcher does not patch the auth seed, so it is impossible to enable encryption, and the app cannot work. If you want to use the regular launcher you would have to reverse engineer the specific client you're using and figure out what it's auth seed is, which I cannot help you with.

**Comment by howarduong** [comment]
Thank you for the answer, understand the principle

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年5月28日 13:12
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [WowLegacyCore/HermesProxy] the recently updated Arctium, can link to HermesProxy, but cannot log in to the account normally. (Issue #38)


You are using the wrong version of the launcher. You need the static auth seed branch. Unfortunately @Fabi<https://github.com/Fabi> has not provided a release for that version. The normal launcher does not patch the auth seed, so it is impossible to enable encryption, and the app cannot work. If you want to use the regular launcher you would have to reverse engineer the specific client you're using and figure out what it's auth seed is, which I cannot help you with.

―

**Comment by Fabi** [comment]
> You are using the wrong version of the launcher. You need the static auth seed branch. Unfortunately @Fabi has not provided a release for that version. The normal launcher does not patch the auth seed, so it is impossible to enable encryption, and the app cannot work. If you want to use the regular launcher you would have to reverse engineer the specific client you're using and figure out what it's auth seed is, which I cannot help you with.

I'll add a release very soon

**Comment by yuritsuki** [comment]
> > You are using the wrong version of the launcher. You need the static auth seed branch. Unfortunately @Fabi has not provided a release for that version. The normal launcher does not patch the auth seed, so it is impossible to enable encryption, and the app cannot work. If you want to use the regular launcher you would have to reverse engineer the specific client you're using and figure out what it's auth seed is, which I cannot help you with.
> 
> I'll add a release very soon. An as I said on the issue in my repo to that person the release won't be 200 files if you use the native build instructions.

Will you also release auth seed + mod loader?

**Comment by Fabi** [comment]
> > > You are using the wrong version of the launcher. You need the static auth seed branch. Unfortunately @Fabi has not provided a release for that version. The normal launcher does not patch the auth seed, so it is impossible to enable encryption, and the app cannot work. If you want to use the regular launcher you would have to reverse engineer the specific client you're using and figure out what it's auth seed is, which I cannot help you with.
> > 
> > 
> > I'll add a release very soon. An as I said on the issue in my repo to that person the release won't be 200 files if you use the native build instructions.
> 
> Will you also release auth seed + mod loader?

Not sure. I don't like seeing end of support frameworks used in here (talking about .net 5). So I might wait until things get right here...

**Comment by ratkosrb** [comment]
We changed it back to 6 specially for you @Fabi
