### ISSUE TITLE
Random logout through the error in Proxy

### ISSUE THREAD

**Issue by Luccifer** [WowLegacyCore/HermesProxy#40]
WoW Ver: 1.14.0 (40618)
ProxyVersion: The most fresh version from GitHub

I was in party with bot, so ranndomly the game logged out with the output of proxy below

![image](https://user-images.githubusercontent.com/1053009/170835280-c267f1bf-a231-46a4-b755-f6603797eefe.png)

**Comment by celguar** [comment]
@Luccifer What core and version of it?

**Comment by Luccifer** [comment]
It's latest CMANGOS builded from sources

**Comment by celguar** [comment]
@Luccifer Cmangos classic has wrong group update flags. I made a PR yesterday, you can try to apply it
[PR](https://github.com/cmangos/mangos-classic/pull/485)
[Patch](https://github.com/cmangos/mangos-classic/commit/2dcf4fa8727e13d18b52cd3cac49dc6527f861f8.patch)

**Comment by celguar** [comment]
should be fixed in https://github.com/cmangos/mangos-classic/commit/42161a19ace84aeae5b1ca4137ed41d27f49b91c
