### ISSUE TITLE
Entering world from WAN\LAN is dropping connection  

### ISSUE THREAD

**Issue by Luccifer** [WowLegacyCore/HermesProxy#42]
CMANGOS Ver: Latest compiled from sources
GameVer: 1.14.0 (40618)
Proxy: Last Released (not compiled)

1) Tryied to connect to dedicated CMANGOS server on VDS (WAN)
2) Tryied to connect through LAN from one computer to another

Login is working, char creation is working, but after pressing "Enter World" it tries to cennect 5 times and then disconnects, also Hermes is going in loop with

Moreover if I try to connect from server-PC with 127.0.0.1 it works as it should. By dedicated or LAN network by subnet 192.168.x.x - not

Hermes config looks for 192.168.x.x and it works till entering world

`21:12:41 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).`

Full Log:

```
21:12:25 | Server  | Server | Hello from Hermes Proxy!
21:12:25 | Server  | Server | Compiled on 05/27/2022 04:57:26.
21:12:25 | Storage | GameData | Loading data files...
21:12:25 | Server  | VersionChecker | Loaded 833 legacy opcodes.
21:12:25 | Server  | VersionChecker | Loaded 1640 modern opcodes.
21:12:25 | Storage | GameData | Finished loading data.
21:12:25 | Server  | Server | Starting REST service...
21:12:25 | Network | NetworkThread | Network Thread Starting
21:12:25 | Server  | Server | Starting Realm manager...
21:12:25 | Server  | RealmManager | Added realm "Sandbox" at 127.0.0.1:8084
21:12:25 | Server  | Server | Starting Login service...
21:12:25 | Server  | Server | BNet Listening on 0.0.0.0:1119...
21:12:25 | Network | NetworkThread | Network Thread Starting
21:12:25 | Server  | Server | World Listening on 0.0.0.0:8084...
21:12:25 | Network | NetworkThread | Network Thread Starting
21:12:29 | Server  | Session | Accepting connection from 127.0.0.1:55152.
21:12:29 | Network | AuthClient | Connecting to auth server...
21:12:30 | Network | AuthClient | Authentication succeeded!
21:12:30 | Network | AuthClient | Received 1 realms.
21:12:30 | Server  | RealmManager | Added realm "Test" at 192.168.88.100:8085
21:12:31 | Network | WorldSocketManager | Instance socket open.
21:12:31 | Server  | WorldSocket | WorldSocket:HandleAuthSession: Client 'testC' authenticated successfully from 127.0.0.1:55163.
21:12:31 | Network | WorldClient | Connecting to world server...
21:12:31 | Network | WorldClient | Connection established!
21:12:31 | Network | WorldClient | Authentication succeeded!
21:12:31 | Warning | WorldSocket | No handler for opcode CMSG_GET_UNDELETE_CHARACTER_COOLDOWN_STATUS (14052)
21:12:31 | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14018)
21:12:31 | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PAY_GET_PRODUCT_LIST (14017)
21:12:31 | Warning | WorldSocket | No handler for opcode CMSG_UPDATE_VAS_PURCHASE_STATES (14072)
21:12:31 | Error   | AuthClient | Socket Closed By Server
21:12:31 | Warning | WorldSocket | No handler for opcode CMSG_BATTLENET_REQUEST (14074)
21:12:32 | Warning | WorldSocket | No handler for opcode CMSG_GET_ACCOUNT_CHARACTER_LIST (14012)
21:12:33 | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14018)
21:12:34 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:34 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:34 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:35 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:35 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:35 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:35 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:35 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:36 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:36 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:36 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:36 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:36 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:37 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:38 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:38 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:38 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:38 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:38 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:38 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:38 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:38 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:38 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:39 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:39 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:39 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:39 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:39 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:40 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:40 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:40 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:40 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:40 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:41 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:41 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:41 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:41 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:41 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:42 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:42 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:42 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:42 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:43 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:43 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:43 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:43 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:43 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:44 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:44 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:44 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:44 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:44 | Error   | WorldSocket | Failed to connect 5 times to world socket, aborting login
21:12:44 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:44 | Warning | WorldSocket | No handler for opcode CMSG_GET_UNDELETE_CHARACTER_COOLDOWN_STATUS (14052)
21:12:44 | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14018)
21:12:44 | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PAY_GET_PRODUCT_LIST (14017)
21:12:44 | Warning | WorldSocket | No handler for opcode CMSG_UPDATE_VAS_PURCHASE_STATES (14072)
21:12:45 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:45 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:45 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:45 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:45 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:46 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:46 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:46 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:46 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:46 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:47 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:47 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:47 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:47 | Server  | WorldSocket | Client disconnected with reason 14.
21:12:47 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:47 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:48 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:48 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:48 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:48 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:48 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:49 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:49 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:49 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:49 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:49 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:50 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:50 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:50 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:50 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:12:50 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
```

And another try:

`21:22:53 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:54 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:54 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:54 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:54 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:54 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:55 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:55 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:55 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:55 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:55 | Warning | WorldSocket | No handler for opcode CMSG_GET_ACCOUNT_CHARACTER_LIST (14012)
21:22:55 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:56 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:56 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:56 | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14018)
21:22:56 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:56 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:56 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:57 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:57 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:57 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:57 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:57 | Network | WorldClient | Waiting to send SMSG_SET_PROFICIENCY (10026).
21:22:57 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:58 | Network | WorldClient | Waiting to send SMSG_SET_PROFICIENCY (10026).
21:22:58 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:58 | Network | WorldClient | Waiting to send SMSG_SET_PROFICIENCY (10026).
21:22:58 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:58 | Network | WorldClient | Waiting to send SMSG_SET_PROFICIENCY (10026).
21:22:58 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:58 | Network | WorldClient | Waiting to send SMSG_SET_PROFICIENCY (10026).
21:22:58 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:58 | Network | WorldClient | Waiting to send SMSG_SET_PROFICIENCY (10026).
21:22:58 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:59 | Network | WorldClient | Waiting to send SMSG_SET_PROFICIENCY (10026).
21:22:59 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:59 | Network | WorldClient | Waiting to send SMSG_SET_PROFICIENCY (10026).
21:22:59 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:59 | Network | WorldClient | Waiting to send SMSG_SET_PROFICIENCY (10026).
21:22:59 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:59 | Network | WorldClient | Waiting to send SMSG_SET_PROFICIENCY (10026).
21:22:59 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:22:59 | Network | WorldClient | Waiting to send SMSG_SET_PROFICIENCY (10026).
21:22:59 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:23:00 | Network | WorldClient | Waiting to send SMSG_SET_PROFICIENCY (10026).
21:23:00 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).
21:23:00 | Network | WorldClient | Waiting to send SMSG_SET_PROFICIENCY (10026).
21:23:00 | Network | WorldClient | Waiting to send SMSG_LOGIN_VERIFY_WORLD (9626).`

**Comment by insunaa** [comment]
This requires some info about your setup, I believe
Does HermesProxy run on the same computer that you start your WoW Client on, or do you run HermesProxy on the Computer that runs the server you want to connect to?

**Comment by Luccifer** [comment]
Both, checking two accounts at the same time from two PCs in the same LAN (if we speaking about lan network) 
On wan - nothing happend after ppressing enter world

**Comment by insunaa** [comment]
How are the ports set up?
Is Hermes listening on 3724 and 8085? Or is the server listening on these ports? Did you configure your server to use the correct ports (such as the realmlist table needing to point to the port that Hermes is listening on, not the server itself, if they're on the same machine)

**Comment by Luccifer** [comment]
Ports setted by default, nothing changed..

**Comment by insunaa** [comment]
Hermes listens on 3724 and 8085, but the server also listens on 3724 and 8085. If you have both of them running on the same computer, without any changes to the ports, then the behaviour is undefined (usually only one program can listen on a port at a time, but I can't guarantee that that'll always be the case).

**Comment by Luccifer** [comment]
ServerClientPC_Proxy
`
![image](https://user-images.githubusercontent.com/1053009/170844883-08279fd4-58e7-4ae7-9dda-a12a74af25f2.png)
`

```
WorldServerPort = 8085
RealmServerPort = 3724
```

ClientPC_Proxy
``

**Comment by 0blu** [comment]
We probably already fixed this already in a previous commit.
I recently tested HermesProxy while playing on another pc and it worked.
I just changed the `ExternalAddress`.

If you somehow still experience this error please reopen the issue.
