### ISSUE TITLE
Modern Client Functionality / Opcode Support

### ISSUE THREAD

**Issue by insunaa** [WowLegacyCore/HermesProxy#59]
### Is there a possibility that HermesProxy will eventually support custom opcodes?

I personally am in favor of custom opcodes, to make better use of the functionality of the newer clients. The new clients support many things, such as the Threat API, the Quest Completion API, more detailed information about some types of data, etc.

IMO such an addition should not interfere at all with servers that do not support the custom opcodes.
We've partially talked about this in my Threat API pull request draft. (https://github.com/WowLegacyCore/HermesProxy/pull/44)

It should be very possible to build a system that can query a server which supports custom (but well defined) opcodes about which custom opcodes it implements and which ones HermesProxy implements, so that a consensus between Hermes and the Server is reached which opcodes Hermes or the Server can process, so that only these opcodes are actually sent.

This would of course require a small protocol to be developed and standards to be set such that those custom opcodes don't get out of hand.

**Comment by MaxtorCoder** [comment]
Highly unlikely, I don't see a reason to do this. If you want custom opcodes you would have the knowledge of using TC, patching the client, etc.

**Comment by 0blu** [comment]
@MaxtorCoder 
Custom opcodes == Modern client opcodes like thread api, warden3, get-early-off-taxi-button.
Mangos could forward support these opcodes.

**Comment by MaxtorCoder** [comment]
I don't see a reason for them to do that honestly, as it is the plan of CMangos to support Legacy clients

**Comment by insunaa** [comment]
Well someone has to lay the groundwork at one end of things, I guess. I can try bothering killerwife and Cyberium until they relent and let me put opcode handlers for *some* modern client features in, as long as they don't interfere with legacy clients.

They're probably not particularly enthused about it tho, because for *some* modern opcodes to be in CMaNGOS, there needs to also be Client/HermesProxy support. So, kind of a chicken & egg situation

**Comment by ratkosrb** [comment]
We should not implement such things unless they are made an official part of cmangos and other emulation projects. Having handlers for opcodes in the main hermes repo that only exist in your own personal fork of the core makes no sense. If it becomes official in cmangos, then we can make it official in hermes. But i can say as the vmangos maintainer, I wouldn't want such things in the core, as the project's goal is to emulate 1.12 vanilla not 1.14 classic.

**Comment by MaxtorCoder** [comment]
Exactly, so I don't see this happening, not now and maybe not even in the future.

**Comment by insunaa** [comment]
It can't happen unless one side does the first step, that's true.
The critical point for me imo: Would it *hurt* HermesProxy in any way to have optional handlers/forwarders for new opcodes?

**Comment by MaxtorCoder** [comment]
Of course not, but it's more that the original server would have to support the optional handlers/forwarders for new opcodes.

**Comment by insunaa** [comment]
Well they don't *have* to. New Opcode support should be optional on all sides and only enabled when agreed upon by both parties.

**Comment by ratkosrb** [comment]
@insunaa I am pretty sure it will not get accepted in cmangos, I know I would be against it if i was part of cmangos. So we will end up with support for functionality that only exists in insunaa/mango-classic fork :laughing:

**Comment by insunaa** [comment]
And when I talk with Cyberium and Killerwife about it they'll send me this screenshot and tell me that's why they're not going to support it
![image](https://user-images.githubusercontent.com/3718129/172021072-60737b3d-79c3-419d-819b-70c3975e874d.png)

**Comment by ratkosrb** [comment]
I have no say what happens in cmangos. If they decide to add it in cmangos, we can add it to hermes as i said, but otherwise it makes no sense for us to have such custom stuff.

**Comment by insunaa** [comment]
I'll talk to them about it. :+1:

**Comment by 0blu** [comment]
I have no idea how modern warden works, but if we don't support `WARDEN3` opcodes there will never be a popular vanilla server that supports Hermes. (looking at "Everlook")

**Comment by ratkosrb** [comment]
I don't think Warden 3 has been reverse engineered and implemented in any public core, but I bet @MaxtorCoder knows for sure.

**Comment by MaxtorCoder** [comment]
Warden indeed has not been reverse engineered for modern clients, 4.3.4 is the max reversed client for it

**Comment by insunaa** [comment]
CMaNGOS says no, so I'm closing the issue tentatively.
I'll start a fork of Hermes and CMaNGOS TBC and work on this issue separately.
I need a few weeks to months to get settled into my new job, then I can dedicate some proper time to this.
