### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by Luccifer** [WowLegacyCore/HermesProxy#7]
Hello!
Used WoW 1.14.0 (40618)
Downloaded release from here, changed the client.WTF portal to 127.0.0.1
The server refuses to login me
![image](https://user-images.githubusercontent.com/1053009/167681229-79aa1f5e-d9ab-4a73-8bfe-dd479646f697.png)

Tried to pull sources and change some strings, etc. for 1.14.3 and used the most updated official client, the same problem.. :( 
Checked firewall, network configurations, port is open, applications (both client and server) are trusted

**Comment by ratkosrb** [comment]
To what server are you trying to connect? If it's not your own server running on the same PC, then did you set the ServerAddress in Hermes' config to the actual IP of the server?

**Comment by Luccifer** [comment]
Do you have any suggestions what server can be used for test, to make it work for sure?

**Comment by coolzoom** [comment]
I tested and it works for both vmangos and cmangos

**Comment by ratkosrb** [comment]
You are using the wrong launcher. You need the static auth seed launcher, not the regular launcher.

**Comment by Luccifer** [comment]
I am using  https://github.com/Arctium/WoW-Launcher/tree/static-auth-seed for launching the game


`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    
    <add key="ClientBuild" value="40618" />
    
    <add key="ClientSeed" value="179D3DC3235629D07113A9B3867F97A7" />
    
    <add key="ServerBuild" value="5875" />
    
    <add key="ServerAddress" value="164.92.206.151" />
    
    <add key="ServerPort" value="3724" />
    
    <add key="ReportedOS" value="OSX" />
    
    <add key="ReportedPlatform" value="PPC" />
    
    <add key="ExternalAddress" value="164.92.206.151" />
    
    <add key="RestPort" value="8081" />
    
    <add key="BNetPort" value="1119" />
    
    <add key="RealmPort" value="8085" />
    
    <add key="InstancePort" value="8086" />
    
    <add key="DebugOutput" value="true" />
  </appSettings>
</configuration>`

**Comment by ratkosrb** [comment]
The release is for the main branch, not for the static auth seed branch. You have to compile this branch yourself.

**Comment by Luccifer** [comment]
Okey, I recompiled the static one, after selecting created char 
it goes in loop with some errors 👯 
![image](https://user-images.githubusercontent.com/1053009/168737095-857bc416-784c-45f7-ac07-5e8d2ea14ea7.png)
![image](https://user-images.githubusercontent.com/1053009/168737126-734d7ac4-1733-4cfa-b926-707b6dd945fd.png)

**Comment by ratkosrb** [comment]
What server or core are you testing it on?

**Comment by Luccifer** [comment]
Last recompiled from scratch CMANGOS for classic

**Comment by ratkosrb** [comment]
I just tested on cmangos classic and it worked without any issue.

**Comment by Luccifer** [comment]
To be clear, so you are using client 1.14.0 (40618) with static-seed launcher from Feb 5, 2022 and CMANGOS from May 1, 2022?

**Comment by ratkosrb** [comment]
The cmangos core is not from the 1st of May, but that shouldn't matter.

**Comment by Luccifer** [comment]
Okey then, looks like I need to open 3 different projects and try debugging :D Will keep it posted after completion :)

**Comment by Luccifer** [comment]
HermesProxy and CMANGOS using same ports for connections, so one locks the port of the other.
What configuration for mangosd.conf for port and hermes  InstancePort and RealmPort should be setted to make it work on localhost?

**Comment by ratkosrb** [comment]
Most likely you're using 8085 for both the proxy's realm socket, and for mangosd. So change some of them to something else.

**Comment by MaxtorCoder** [comment]
You should definitely use different ports, as long as the port in the settings are set to the correct ports.

**Comment by ratkosrb** [comment]
So use a different number...

**Comment by Luccifer** [comment]
If I use 8085 for gameserver and 8086 InstancePort and  8084 RealmPort:
![image](https://user-images.githubusercontent.com/1053009/168772404-ba3bdac6-155b-4ffe-b557-2c4b80be17d2.png)

**Comment by ratkosrb** [comment]
You've enabled warden on the server. Warden emulation is not implemented, so the proxy instantly disconnects on receiving the warden packet. You need to fully disable the server anticheat.

**Comment by Luccifer** [comment]
Okey, thanks, m8s, it works for now. Spotted the bug when Hermes closes the process with errors like this:
![image](https://user-images.githubusercontent.com/1053009/168787798-7b7e6020-5be5-4832-b249-45ef264a832e.png)
This can be catched when looting (mobs or quest objects looting), frequently appearing.
Suppose it should be another issue already in another topic :)
Good luck with development!
