### ISSUE TITLE
Can you package the Arctium WoW Launcher as a separate exe

### ISSUE THREAD

**Issue by howarduong** [WowLegacyCore/HermesProxy#72]
Can you package the Arctium WoW Launcher as a separate exe

**Comment by MaxtorCoder** [comment]
The developer of the Arctium WoW Launcher was planning of making a release for the branch that we use soon.

**Comment by BigKananga** [comment]
> The developer of the Arctium WoW Launcher was planning of making a release for the branch that we use soon.

Any news about this?

**Comment by 0blu** [comment]
You can now download the signed launcher from the release tab https://github.com/Arctium/WoW-Launcher/releases/tag/latest
Use the `--staticseed` option to make hermes work.
