### ISSUE TITLE
Authentication failed  for account

### ISSUE THREAD

**Issue by qazaassqz** [WowLegacyCore/HermesProxy#75]
![图像_2022-07-16_184321098](https://user-images.githubusercontent.com/46471588/179351687-4ec2f4ab-5ab3-4430-a034-0c30e9dc2fcd.png)

I followed the instructions step by step, and finally the authentication failed when logging in to the server. Can you help me solve this problem?

**Comment by ratkosrb** [comment]
You might be using the wrong launcher. You need the static auth seed launcher.

**Comment by sdelanoue** [comment]
Hi,
Cannot connect as well 
I downloaded Arctium static version from :
https://github.com/Arctium/WoW-Launcher/tree/static-auth-seed
	
builded it self contained :
 dotnet publish -r win-x64 /p:Configuration="Release" /p:platform="x64" --self-contained
Microsoft (R) Build Engine version 17.2.0+41abc5629 pour .NET
Copyright (C) Microsoft Corporation. Tous droits réservés.

  Identification des projets à restaurer...
  Tous les projets sont à jour pour la restauration.
  Arctium.WoW.Launcher -> D:\Documents\WoW-Launcher-static-auth-seed\build\Release\bin\Arctium WoW Launcher.dll
     Création de la bibliothèque ..\build\Release\bin\native\Arctium WoW Launcher.lib et de l'objet ..\build\Release\bin\native\Arctium WoW Launcher.exp
  Optimisation de la taille des assemblys, ce qui peut entraîner un changement de comportement de l'application. Veillez à effectuer des tests après la publication. Consultez https://aka.ms/dotnet-illink
  Arctium.WoW.Launcher -> D:\Documents\WoW-Launcher-static-auth-seed\build\Release\bin\win-x64\publish\

started if after copying all files in wow classic 1.14.3 dir
changed wow config to have SET portal "127.0.0.1"
changed HermesProxy.dll.config to have     <add key="ServerAddress" value="my private 1.12.1 server" />

started Actium launcher :
   _____________World of Warcraft___________
                   _   _
    /\            | | (_)
   /  \   _ __ ___| |_ _ _   _ _ __ ___
  / /\ \ | '__/ __| __| | | | | '_ ` _ \
 / ____ \| | | (__| |_| | |_| | | | | | |
/_/    \_\_|  \___|\__|_|\__,_|_| |_| |_|

___________WoW Client Launcher___________
            https://arctium.io

Operating System: Microsoft Windows 10.0.19043
Mode: Custom Server (ClassicEra)

Starting WoW client...
Refreshing client data...
[Certificate Bundle] Patching...
[Certificate Bundle] Done.

[Certificate Signature Modulus] Patching...
[Certificate Signature Modulus] Done.

[ConnectTo Modulus] Patching...
[ConnectTo Modulus] Done.

[ChangeProtocol (GameCrypt) Modulus] Patching...
[ChangeProtocol (GameCrypt) Modulus] Done.

[Login Portal] Patching...
[Login Portal] Done.

[Version URL] Patching...
[Version URL] Done.

[Launcher Login Registry] Patching...
[Launcher Login Registry] Done.

Waiting for client initialization...
Waiting for client initialization...
Refreshing client data...
[Integrity0] Adding...
[Integrity0] Done.

[Integrity1] Adding...
[Integrity1] Done.

[Integrity2] Adding...
[Integrity2] Done.

[Integrity3] Adding...
[Integrity3] Done.

[Jump2014797] Adding...
[Jump2014797] Done.

[Jump2014460] Adding...
[Jump2014460] Done.

[Jump2011127] Adding...
[Jump2011127] Done.

[Jump2012396] Adding...
[Jump2012396] Done.

[Jump2045901] Adding...
[Jump2045901] Done.

[Jump2039756] Adding...
[Jump2039756] Done.

[Jump2041362] Adding...
[Jump2041362] Done.

[Jump2040816] Adding...
[Jump2040816] Done.

[Jump2147570] Adding...
[Jump2147570] Done.

[Jump2753745] Adding...
[Jump2753745] Done.

[Jump2754077] Adding...
[Jump2754077] Done.

[Jump2750353] Adding...
[Jump2750353] Done.

[Jump2751689] Adding...
[Jump2751689] Done.

[Jump2893047] Adding...
[Jump2893047] Done.

[Jump2902675] Adding...
[Jump2902675] Done.

[Jump2903005] Adding...
[Jump2903005] Done.

[Jump2900610] Adding...
[Jump2900610] Done.

[Jump2962620] Adding...
[Jump2962620] Done.

[Jump2963865] Adding...
[Jump2963865] Done.

[Jump2966685] Adding...
[Jump2966685] Done.

[Jump3520109] Adding...
[Jump3520109] Done.

[Jump3517577] Adding...
[Jump3517577] Done.

[Jump3516239] Adding...
[Jump3516239] Done.

[Jump4649058] Adding...
[Jump4649058] Done.

[Jump4653965] Adding...
[Jump4653965] Done.

[Jump4647529] Adding...
[Jump4647529] Done.

[Jump4648504] Adding...
[Jump4648504] Done.

[Jump5737793] Adding...
[Jump5737793] Done.

[Jump5737248] Adding...
[Jump5737248] Done.

[Jump5743405] Adding...
[Jump5743405] Done.

[Jump5736278] Adding...
[Jump5736278] Done.

[Jump5764285] Adding...
[Jump5764285] Done.

[Jump5758640] Adding...
[Jump5758640] Done.

[Jump5757601] Adding...
[Jump5757601] Done.

[Jump5759165] Adding...
[Jump5759165] Done.

[Jump5952774] Adding...
[Jump5952774] Done.

[Jump5956688] Adding...
[Jump5956688] Done.

[Jump15771773] Adding...
[Jump15771773] Done.

[Jump15768051] Adding...
[Jump15768051] Done.

[Jump15769347] Adding...
[Jump15769347] Done.

[Jump15771429] Adding...
[Jump15771429] Done.

[Jump17542397] Adding...
[Jump17542397] Done.

[Jump17541524] Adding...
[Jump17541524] Done.

[Jump17539993] Adding...
[Jump17539993] Done.

[Jump17540977] Adding...
[Jump17540977] Done.

[Jump28019482] Adding...
[Jump28019482] Done.

[Jump28025894] Adding...
[Jump28025894] Done.

[Jump28020032] Adding...
[Jump28020032] Done.

[Jump28018480] Adding...
[Jump28018480] Done.

[Jump29053773] Adding...
[Jump29053773] Done.

[Jump29049117] Adding...
[Jump29049117] Done.

[Jump29047503] Adding...
[Jump29047503] Done.

[Jump29048570] Adding...
[Jump29048570] Done.

[Jump29063880] Adding...
[Jump29063880] Done.

[Jump29095101] Adding...
[Jump29095101] Done.

[Jump29091379] Adding...
[Jump29091379] Done.

[Jump29094761] Adding...
[Jump29094761] Done.

[Jump29092700] Adding...
[Jump29092700] Done.

[Jump29109309] Adding...
[Jump29109309] Done.

[Jump29102905] Adding...
[Jump29102905] Done.

[Jump29103858] Adding...
[Jump29103858] Done.

[Jump29122880] Adding...
[Jump29122880] Done.

[Jump29123421] Adding...
[Jump29123421] Done.

[Jump29121876] Adding...
[Jump29121876] Done.

[Jump29128925] Adding...
[Jump29128925] Done.

[Jump29180902] Adding...
[Jump29180902] Done.

[Jump29173135] Adding...
[Jump29173135] Done.

[Jump29174150] Adding...
[Jump29174150] Done.

[Jump29174691] Adding...
[Jump29174691] Done.

Refreshing client data...
[CustomAuthSeedFunction] Adding...
[CustomAuthSeedFunction] Done.

[CertBundle] Adding...
[CertBundle] Done.

[CertCommonName] Adding...
[CertCommonName] Done.

Done :)
You can login now.


Started HermesProxy :
16:16:45 | Server  | Server | Hello from Hermes Proxy!
16:16:45 | Server  | Server | Compiled on 05/27/2022 04:57:26.
16:16:45 | Storage | GameData | Loading data files...
16:16:45 | Server  | VersionChecker | Loaded 833 legacy opcodes.
16:16:45 | Server  | VersionChecker | Loaded 1640 modern opcodes.
16:16:46 | Storage | GameData | Finished loading data.
16:16:46 | Server  | Server | Starting REST service...
16:16:46 | Network | NetworkThread | Network Thread Starting
16:16:46 | Server  | Server | Starting Realm manager...
16:16:46 | Server  | RealmManager | Added realm "Sandbox" at 127.0.0.1:8084
16:16:46 | Server  | Server | Starting Login service...
16:16:46 | Server  | Server | BNet Listening on 0.0.0.0:1119...
16:16:46 | Network | NetworkThread | Network Thread Starting
16:16:46 | Server  | Server | World Listening on 0.0.0.0:8084...
16:16:46 | Network | NetworkThread | Network Thread Starting


but when I log :
16:17:20 | Server  | Session | Accepting connection from 127.0.0.1:63025.
16:17:20 | Error   | SSLSocket | System.ComponentModel.Win32Exception (0x8009030D): Les informations d'identification fournies au package n'ont pas été reconnues
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
   at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
   at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)

**Comment by qazaassqz** [comment]
> You might be using the wrong launcher. You need the static auth seed launcher.

Also ,I downloaded Arctium static version from :
https://github.com/Arctium/WoW-Launcher/tree/static-auth-seed ,the latest release 2022-04-10.I'm sure all the steps are done according to the instructions

**Comment by ratkosrb** [comment]
The release is not for the static auth seed branch. It's for the normal launcher.

**Comment by sdelanoue** [comment]
I'm totally confused there, you said "You need the static auth seed launcher." end now "The release is not for the static auth seed branch"

on widow branch (the main and only other one) I seed those 4 files 

Custom.Server.Launcher.Mods.Silent.Windows.zip
3.06 MB 10 Apr 2022
Custom.Server.Launcher.Mods.Windows.zip
3.05 MB 10 Apr 2022
Custom.Server.Launcher.Silent.Windows.zip
4.9 MB 27 Nov 2021
Custom.Server.Launcher.Windows.zip
4.04 MB 27 Nov 2021

none of them are static auth
so is it the ones you are talking about ?

of shall I rebuild from source with particular parameters ?

**Comment by ratkosrb** [comment]
No release is provided for that branch. You need to compile it yourself.

**Comment by sdelanoue** [comment]
which brnch are you tlaking about ?

is it https://github.com/Arctium/WoW-Launcher/tree/static-auth-seed ?
or https://github.com/Arctium/WoW-Launcher/tree/windows

**Comment by 0blu** [comment]
Stale, probably fixed by new releases from Arctium
