### ISSUE TITLE
need to handle latest Classic client V44403

### ISSUE THREAD

**Issue by sdelanoue** [WowLegacyCore/HermesProxy#77]
HermesProxy do not handle client 44403

I tried with no success (LogonChallenge fail leading to answer user do not exist) by adding enum for version 44403

probably the seed is not valid for client 44403 or I missed something

13:07:12 | Server  | Server          | Starting Hermes Proxy...
13:07:12 | Server  | Server          | Version 2022-06-12 3.0.1+50(6d61a9b)
13:07:12 | Storage | GameData        | Loading data files...
13:07:13 | Server  | VersionChecker  | Loaded 833 legacy opcodes.
13:07:13 | Server  | VersionChecker  | Loaded 1639 modern opcodes.
13:07:15 | Storage | GameData        | Finished loading data.
13:07:15 | Server  | Server          | Starting REST service...
13:07:15 | Network | NetworkThread   | Network Thread Starting
13:07:15 | Server  | Server          | Starting Login service...
13:07:15 | Server  | Server          | BNet Listening on 0.0.0.0:1119...
13:07:15 | Server  | Server          | World Listening on 0.0.0.0:8084...
13:07:15 | Network | NetworkThread   | Network Thread Starting
13:07:15 | Network | NetworkThread   | Network Thread Starting
13:07:56 | Server  | BnetTcpSession  | Accepting connection from 127.0.0.1:55549.
13:08:08 | Network | AuthClient      | C P>S | Connecting to auth server...
13:08:47 | Error   | AuthClient      | Login failed. Reason: FAIL_UNKNOWN_ACCOUNT
13:09:14 | Server  | BnetTcpSession  | Accepting connection from 127.0.0.1:55693.
13:09:20 | Network | AuthClient      | C P>S | Connecting to auth server...
13:11:34 | Error   | AuthClient      | Login failed. Reason: FAIL_UNKNOWN_ACCOUNT

portion of code in authClient.cs line 412:
            AuthResult error = (AuthResult)packet.ReadUInt8();
            if (error != AuthResult.SUCCESS)
            {
                Log.Print(LogType.Error, $"Login failed. Reason: {error}");
                SetAuthResponse(error);
                return;
            }

**Comment by ratkosrb** [comment]
Who told you that you can use this client? You need 1.14.0.40618 or 2.5.2.40892. It only works with those specific versions.

**Comment by sdelanoue** [comment]
where can I find it ? got min from bnet client from my blizzard account

**Comment by ratkosrb** [comment]
If you google the version you'll find links.
