### ISSUE TITLE
Abilities not always showing up

### ISSUE THREAD

**Issue by Mige5** [WowLegacyCore/HermesProxy#80]
Abilites not always showing up on login and have to relog to fix.

- theyr not showing up anywhere in spellbook or action bars.

**Comment by Lihvar** [comment]
I have encountered this in earlier versions of Hermes as well, on both Classic and TBC, but this doesn't seem to be the case anymore, I think this has been resolved in newer versions of Hermes

**Comment by 0blu** [comment]
Ah yes, this issue was fixed. I just missed to close this one
