### ISSUE TITLE
Login failed. Reason: WRONG_BUILD_NUMBER

### ISSUE THREAD

**Issue by SoongXiaoTong** [WowLegacyCore/HermesProxy#84]
Hello Guys,
Sorry to trouble your time, but I really can not found how I can solve this error.
I tried HermesProxy for vmangos repack V20, port 3724 for realmlist, 8085 for mangosd, client 1.14.0 40618 to connection will have below error. may I get your help to known what happened? how can I solve that?

HermesProxy: HermesProxy.Windows.27-05-2022
Arctium WoW Launcher: [Launcher Signed (2022/08/19)] [Windows.x86_64.zip]
Core: VMangos Repack V20

config file setup with:
    add key="ClientBuild" value="40618" 
    add key="ClientSeed" value="179D3DC3235629D07113A9B3867F97A7" 
    add key="ServerBuild" value="5875" 

================HermesProxy Error=================
10:22:11 | Server  | Server | Hello from Hermes Proxy!
10:22:11 | Server  | Server | Compiled on 05/27/2022 04:57:26.
10:22:11 | Storage | GameData | Loading data files...
10:22:11 | Server  | VersionChecker | Loaded 833 legacy opcodes.
10:22:11 | Server  | VersionChecker | Loaded 1640 modern opcodes.
10:22:11 | Storage | GameData | Finished loading data.
10:22:11 | Server  | Server | Starting REST service...
10:22:11 | Network | NetworkThread | Network Thread Starting
10:22:11 | Server  | Server | Starting Realm manager...
10:22:11 | Server  | RealmManager | Added realm "Sandbox" at 127.0.0.1:8084
10:22:11 | Server  | Server | Starting Login service...
10:22:11 | Server  | Server | BNet Listening on 0.0.0.0:1119...
10:22:11 | Network | NetworkThread | Network Thread Starting
10:22:11 | Server  | Server | World Listening on 0.0.0.0:8084...
10:22:11 | Network | NetworkThread | Network Thread Starting
10:22:32 | Server  | Session | Accepting connection from 127.0.0.1:54365.
10:22:32 | Debug   | Session | Service 1698982289 Method 1 Token 0
10:22:32 | Debug   | Session | Service 233634817 Method 1 Token 1
10:22:32 | Network | AuthClient | Connecting to auth server...
10:22:32 | Debug   | AuthClient | Received opcode LOGON_CHALLENGE size 119.
10:22:32 | Debug   | AuthClient | Received opcode LOGON_PROOF size 2.
10:22:32 | Error   | AuthClient | Login failed. Reason: WRONG_BUILD_NUMBER
10:22:32 | Debug   | Session | Service 1698982289 Method 7 Token 2

================Realmd Error=================
Accepting connection from ''
[AuthChallenge] Account 'ADMIN' using IP '' is using 'zhCN' locale (4)
[AuthChallenge] Account ADMIN tried to login with modified client!

**Comment by ratkosrb** [comment]
Open realmd.conf in the server folder and change StrictVersionChecking to 0.

**Comment by SoongXiaoTong** [comment]
hi ratkosrb,
thank you so much for your replay, I changed StrictVersionChecking to 0 and close warden, but i still get below error, may i get your help?

13:15:35 | Server  | Server | Hello from Hermes Proxy!
13:15:35 | Server  | Server | Compiled on 05/27/2022 04:57:26.
13:15:35 | Storage | GameData | Loading data files...
13:15:35 | Server  | VersionChecker | Loaded 833 legacy opcodes.
13:15:35 | Server  | VersionChecker | Loaded 1640 modern opcodes.
13:15:35 | Storage | GameData | Finished loading data.
13:15:35 | Server  | Server | Starting REST service...
13:15:35 | Network | NetworkThread | Network Thread Starting
13:15:35 | Server  | Server | Starting Realm manager...
13:15:35 | Server  | RealmManager | Added realm "Sandbox" at 127.0.0.1:8084
13:15:35 | Server  | Server | Starting Login service...
13:15:35 | Server  | Server | BNet Listening on 0.0.0.0:1119...
13:15:35 | Network | NetworkThread | Network Thread Starting
13:15:35 | Server  | Server | World Listening on 0.0.0.0:8084...
13:15:35 | Network | NetworkThread | Network Thread Starting
13:15:54 | Server  | Session | Accepting connection from 127.0.0.1:58649.
13:15:55 | Debug   | Session | Service 1698982289 Method 1 Token 0
13:15:55 | Debug   | Session | Service 233634817 Method 1 Token 1
13:15:55 | Network | AuthClient | Connecting to auth server...
13:15:55 | Debug   | AuthClient | Received opcode LOGON_CHALLENGE size 119.
13:15:55 | Debug   | AuthClient | Received opcode LOGON_PROOF size 26.
13:15:55 | Network | AuthClient | Authentication succeeded!
13:15:55 | Debug   | Session | Service 233634817 Method 7 Token 2
13:15:55 | Debug   | Session | Service 1658456209 Method 30 Token 3
13:15:55 | Debug   | Session | Service 1658456209 Method 31 Token 4
13:15:55 | Debug   | Session | Service 1069623117 Method 1 Token 5
13:15:55 | Debug   | Session | Service 1069623117 Method 10 Token 6
13:15:55 | Debug   | Session | Service 1069623117 Method 1 Token 7
13:15:55 | Debug   | Session | Service 1069623117 Method 1 Token 8
13:15:55 | Debug   | AuthClient | Received opcode REALM_LIST size 50.
13:15:55 | Network | AuthClient | Received 1 realms.
13:15:55 | Server  | RealmManager | Added realm "Lightbringer" at 127.0.0.1:8085
13:15:57 | Debug   | Session | Service 1069623117 Method 1 Token 9
13:15:57 | Network | WorldSocketManager | Instance socket open.
13:15:57 | Debug   | WorldSocket | Sending opcode SMSG_AUTH_CHALLENGE (12360).
13:15:57 | Debug   | WorldSocket | Received opcode CMSG_AUTH_SESSION (14181).
13:15:57 | Error   | WorldSocket | WorldSocket.HandleAuthSession: Authentication failed for account: 1 ('admin') address: 127.0.0.1:58654
13:15:57 | Error   | AuthClient | Socket Closed By Server
13:15:57 | Debug   | Session | Service 1698982289 Method 7 Token 10

**Comment by SoongXiaoTong** [comment]
![image](https://user-images.githubusercontent.com/113569749/190328809-f8d66698-ba09-4313-8556-69a56a5dd148.png)

got this, trying...

**Comment by SoongXiaoTong** [comment]
works after compiled static auth seed luancher. close this issue, thank you ratkosrb.
