### ISSUE TITLE
Support for Wotlk 3.4

### ISSUE THREAD

**Issue by DimaSheiko** [WowLegacyCore/HermesProxy#86]
Please add support for the latest version of wotlk classic. I have been logging into this repository almost every day since wotlk classic was released to see if there is any movement, sadly there is not. I would love to support the development but I have no C# skills whatsoever.
Is there any other way to support?

**Comment by ratkosrb** [comment]
My goal with this project was to make Vanilla and TBC playable with the new clients, because the original ones have too many performance issues. That is not the case with 3.3.5 which runs much smoother in comparison. And the new WotLK client is even missing major features like the built in quest helper which shows objectives on the map, and the random dungeon finder (my favorite feature of the expansion). So I have no plans to work on supporting the 3.4.0 client. My main goals for Hermes have been accomplished, and I've stepped off to focus on other projects. Of course if somebody else wants to take it upon themselves and add 3.4.0 support they are free to do so, but I'd rather do other things myself.

**Comment by DimaSheiko** [comment]
Thank you for the clarification. Best regards!

**Comment by Socom12** [comment]
> My goal with this project was to make Vanilla and TBC playable with the new clients, because the original ones have too many performance issues. That is not the case with 3.3.5 which runs much smoother in comparison. And the new WotLK client is even missing major features like the built in quest helper which shows objectives on the map, and the random dungeon finder (my favorite feature of the expansion). So I have no plans to work on supporting the 3.4.0 client. My main goals for Hermes have been accomplished, and I've stepped off to focus on other projects. Of course if somebody else wants to take it upon themselves and add 3.4.0 support they are free to do so, but I'd rather do other things myself.

the wotlk client is ancient though, the classic one is much better

**Comment by MaxtorCoder** [comment]
> > My goal with this project was to make Vanilla and TBC playable with the new clients, because the original ones have too many performance issues. That is not the case with 3.3.5 which runs much smoother in comparison. And the new WotLK client is even missing major features like the built in quest helper which shows objectives on the map, and the random dungeon finder (my favorite feature of the expansion). So I have no plans to work on supporting the 3.4.0 client. My main goals for Hermes have been accomplished, and I've stepped off to focus on other projects. Of course if somebody else wants to take it upon themselves and add 3.4.0 support they are free to do so, but I'd rather do other things myself.
> 
> 
> 
> the wotlk client is ancient though, the classic one is much better

What 🤣 You are aware that WOTLK Classic is a thing... Right...?

**Comment by ghost** [comment]
Ratko brate i wow saigrace, napravi nam taj 3.4 client da radi za 3.3.5 ruke ti se pozlatile!

**Comment by Francoporto** [comment]
Hello, i know you are not working in this project anymore but... can you do that now that the last version of Wotlk is released ? :(
It's such horrible to play with the 3.3.5 client.

**Comment by MarioLConcheso** [comment]
> Hello, i know you are not working in this project anymore but... can you do that now that the last version of Wotlk is released ? :( It's such horrible to play with the 3.3.5 client.

That would be awesome!
