### ISSUE TITLE
Domain name in Realmlist

### ISSUE THREAD

**Issue by 1nf3sT** [WowLegacyCore/HermesProxy#9]
Trying to connect to a server which have different IP's for Login server and realm. Could that be why I get this error? 
23:53:23 | Network | AuthClient | Connecting to auth server...
23:53:23 | Network | AuthClient | Authentication succeeded!
23:53:23 | Network | AuthClient | Received 2 realms.
23:53:23 | Error   | AuthClient | Packet Read Error: An invalid IP address was specified.

**Comment by ratkosrb** [comment]
Currently the app only works with IP addresses, not domains. The server you're connecting to is sending a domain in the realmlist, so it throws this error.

**Comment by 1nf3sT** [comment]
Is this possible to fix in the future?

**Comment by ratkosrb** [comment]
Yes it's possible.
