### ISSUE TITLE
HermesProxy - Release 27-05-2022

### ISSUE THREAD

**Issue by MaouOROCHI** [WowLegacyCore/HermesProxy#90]
Hi developer \ developers,
I don't know if you were informed about this bug or problem, whatever you call it, but it exists.
When you go past the login screen, in the character menu, a black screen appears, and you can't see any created characters, everything is black.

*footnote: it lets you create the character, but after you've created it you can't see it anymore, it's a black screen with no background and no trace of the character.

I have attached a picture below:
![Problem in the main menu of created characters](https://user-images.githubusercontent.com/116728470/198024292-6257d0de-76f8-4920-a924-cb08104e93a9.PNG)

I noticed this problem with the other releases as well: Release 21-05-2022 (v2.0); Release 09-05-2022 (v1.0).
Specifically, it is only on the burning crusade classic. The wow classic version works fine.
All the best!

**Comment by ratkosrb** [comment]
What server are you testing on?

**Comment by MaouOROCHI** [comment]
> What server are you testing on? The black screen indicates the server is not replying with the character list packet. In the latest cmangos core, with anticheat enabled, the server does not send the character list until the client replies to the first warden packet. This is to prevent fake clients like Hermes from connecting. If this is indeed a server using the same anticheat as cmangos, then you need to ask the owners to disable the anticheat to connect.

On the Atlantiss server, with the Burning Crusade expansion.

**Comment by MaouOROCHI** [comment]
In the case of a TBC repack, what should be changed and especially where?

I specify that I am neither an IT expert nor a programmer, just a simple gamer.

However, I'll also test it on a burning crusade repack, I'll report back in a few hours.

**Comment by ratkosrb** [comment]
In the case of cmangos, open anticheat.conf with notepad and set these settings to 0.

Enable = 0
Warden.Enable = 0

**Comment by MaouOROCHI** [comment]
> In the case of cmangos, open anticheat.conf with notepad and set these settings to 0.
> 
> Enable = 0 Warden.Enable = 0

I understand, thank you!

**Comment by MaouOROCHI** [comment]
> I don't know what TBC servers it works with, I've only tested locally.

I understand, thank you very much for your time.
