### ISSUE TITLE
Delayed actions compared to 1.12 version

### ISSUE THREAD

**Issue by Zavve** [WowLegacyCore/HermesProxy#92]
**Describe the bug**
I get a delay for about 10 frames on all actions I do when I use the proxy. Is there a workaround for this? See attached mp4

**Game Server**
Everlook 1.12 and 1.14

**Hermes Proxy Version**
Latest from github

https://user-images.githubusercontent.com/117593435/200189899-d882af86-fd42-49b1-bf32-42a7294c4e9c.mp4

**Comment by 0blu** [comment]
Related to artificial lag introduced for #104

**Comment by 0blu** [comment]
Apparently it is not fixed.

**Comment by Lihvar** [comment]
This is probably a bi-product of the artificial delay, your spell animations don't get stuck but you get delay, really also depends on values you put for the delay. In case you aren't using the artificial delay then I'm not really sure what could be causing this.

**Comment by pabs-wow** [comment]
I installed the Quartz addon for 1.14, and it shows an additional 150-200ms latency compared to what I get on 1.12.
