### ISSUE TITLE
General chat not changing zone.

### ISSUE THREAD

**Issue by Daribon** [WowLegacyCore/HermesProxy#93]
**Describe the bug**
If you change leave a zone and enter a new zone, you will not join the new zones general chat. 
You will remain in the old zones general chat.

**Game Server**
1.12.1 VMaNGOS

**Hermes Proxy Version**
![WindowsTerminal_BlMkroQh5g](https://user-images.githubusercontent.com/6137576/201544514-4956ab3b-b4e8-4f1c-b721-a397149b817e.png)

**Comment by 0blu** [comment]
Fix in newest release (ref 02e5d2a0bf950d58b622358124c5481ecd4dfa91)
