### ISSUE TITLE
Error at retrieving character list.

### ISSUE THREAD

**Issue by Dom-Juan** [WowLegacyCore/HermesProxy#97]
I cant login because the game dont get the character list.

![error](https://user-images.githubusercontent.com/35587574/202593405-c8f0950e-22c7-46bd-905f-1242b9ff7669.png)

**Comment by dackota** [comment]
This just started happening today to me too. It was working fine with Everlook till just a few hours ago but I haven't changed anything on my end.

**Comment by ciroc9078** [comment]
yup wont load for me

**Comment by ratkosrb** [comment]
I talked with the server owner, and it's actually a bug in the server. It can get randomly bugged depending on the latency. I've submitted a fix to them. Wait for them to update it.
